### ISSUE TITLE
Manifest creation tool tweaks

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1018]
#### Tasks
- [ ] Add "Reload" button to enable a user to reload the page and start with a fresh import/create/validate workflow.
- [ ] Introduce a default file name for all generated .checkm files: "merritt.checkm"
- [x] Link to manifest tool documentation page
