### ISSUE TITLE
[Minio/UCSB] Set up UCSB Minio stage environment

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#102]
Top-level tracker for all tickets related to setting up external Minio storage at <PROVIDER> in <ENV>. Clone this ticket first. (Repeat for stage and production.)
 - [ ] Create/update ops page ⇒ #162553661
 - [ ] Gather info / get access ⇒ clone ticket #162553480
 - [ ] Run test suite ⇒ clone ticket #162552948
 - [ ] Add storage node ⇒ clone ticket #162552921
 - [ ] Configure and redeploy/restart storage service ⇒ clone ticket #162552784
 - [ ] Add storage node to inventory database ⇒ clone ticket #162552690
 - [ ] Redeploy/restart audit and replication service ⇒ clone ticket #162552653
 - [ ] Set up monitors ⇒ clone ticket #162552624
