### ISSUE TITLE
[Minio/<PROVIDER> checklist] Gather info / get access for <ENV>

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#106]
Coordinate with the storage provider to make sure their Minio server's working and we have the info & firewall holes we need to get access to it.

To test access to the Minio bucket, use the AWS command line from a Merritt server whitelisted by the provider:

```
AWS_ACCESS_KEY_ID=<access key> AWS_SECRET_ACCESS_KEY=<secret key> \
  aws --endpoint-url <URL> s3 ls
```

This should output the bucket name.

(Note: more exhaustive testing is covered later; this is just to make sure the URL is correct, the credentials are correct, and the IP is whitelisted.)

**TO DO:** fill in list of IP addresses here that we’ll need to give external storage providers. (Hopefully a short list if #160468186 works out.)
 - [ ] Give <PROVIDER> list of Merritt <ENV> server IP addresses to whitelist
 - [ ] Get server endpoint URL and bucket name for <ENV> from <PROVIDER>
 - [ ] Get credentials for <ENV> from <PROVIDER>
 - [ ] Test access to the bucket with aws s3 ls (see above)
 - [ ] Update ops page
