### ISSUE TITLE
Upgrade Merritt UI to Rails 6 / Ruby 3

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1071]
## Current Config
- Ruby 2.6.6 - **💀 EOL 2022-03-31**
- Rails 5.2 - **💀 EOL 2022-06-01**

## Repo Status
- Docker based ruby apps
  - https://github.com/CDLUC3/merritt-docker/pull/39
    - Merged 
  - https://github.com/CDLUC3/mrt-integ-tests/pull/7
    - Merged 
  - Lambda based ruby apps
    - https://github.com/CDLUC3/mrt-admin-lambda/pull/50
      - This cannot be merged until a ruby3 lambda runtime is available 
  - Server deployed ruby apps 
    - https://github.com/CDLUC3/mrt-cron/pull/5
    - https://github.com/CDLUC3/mrt-atom/pull/1
    - https://github.com/CDLUC3/mrt-dashboard/pull/132

## Upgrade info
- [Rails 6 Release Notes](https://edgeguides.rubyonrails.org/6_0_release_notes.html)
  - **💀 6.0 EOL 2023-03-01**
  - **💀 6.1 EOL Not specified**
  - Rails 6 requires Ruby 2.5.0 or newer. ✅
  - [5.2 to 6 Upgrade Guide](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-5-2-to-rails-6-0)
    - [ ] Things are working without Webpacker, do I need to switch to it? 
    - [ ] See https://github.com/DMPRoadmap/roadmap/wiki/Rails-Upgrade-Notes for hostname
- [Rails 7 Release Notes](https://guides.rubyonrails.org/7_0_release_notes.html)
  - Rails 7 requires Ruby 2.7.0 or newer.
  - [6.1 to 7 Upgrade Guide](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-6-1-to-rails-7-0)
- [Ruby 2.7 Release Notes](https://www.ruby-lang.org/en/news/2019/12/25/ruby-2-7-0-released/), **💀 EOL 2023-03-31**
- [Ruby 3.0 Release Notes](https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/), **💀 EOL 2024-03-31**
- [Ruby 3.1 Release Notes](https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/) **💀 EOL 2025-12-25**

## Tasks
- Rails 6.1/Ruby 2.6
  - [x] Run rails coverage with rails6
    - https://github.com/CDLUC3/mrt-dashboard/pull/132 
  - [x] User tests with rails6 running in Docker stack
  - [x] Run mrt-integ-tests with rails6 running in Docker stack
- Rails 6.1/Ruby 2.7 
  - Skipping this step.  Checked with Brian and Scott to confirm skipping 
- Rails 6.1/Ruby 3.0
  - [x] Update DEV box Ruby to 3.04
    - Why do we care about the local install if everything runs in Docker?
    - On the DEV box, the following is run from the command line before initiating a full docker test
      - `rubocop`
      - `rubocop -A` to bring code into compliance with standards
      - `bundle exec rspec xxx` to test a subset of unit tests
      - `bundle exec rails coverage` to test code coverage before committing changes
      - `irb` for debugging code
  - [x] Run rails coverage
  - [x] Run user tests in the docker stack
  - [x] Run mrt-integ-tests with rails6 running in Docker stack
  - [x] Complete MySql 8 upgrade - stage
    - https://github.com/cdlib/cdlsys/issues/25  
  - [ ] Upgrade Ruby on Stage box
  - [ ] Deploy rails6 to Stage and test
- Plan prod deploy
  - [ ] Complete MySql 8 upgrade - prod
    - https://github.com/cdlib/cdlsys/issues/26 
  - [ ] Coordinate ruby update with rails 6 deployment with load balancer add/remove
- Consistency Reports - Ruby 3 upgrade
  - [ ] Upgrade Ruby on mrt-batch stage
  - [ ] Deploy changes to stage
  - [ ] Upgrade Ruby on mrt-batch prod
  - [ ] Deploy changes to prod  
- Docker stack
  - [x] Upgrade docker stack to MySql8 / Ruby 3
  - [ ] Push images to ECR
  - [ ] Run all integration builds  
- Migrate to ruby 3 runtime for lambda
  - [ ] Revert the following commit
    -  https://github.com/CDLUC3/mrt-admin-lambda/pull/50/commits/b890c5d74541857617109c1caed249c94e33f9f8

**Comment by elopatin-uc3** [comment]
Ruby v3.04 is supported on Amazon Linux 3.

**Comment by mreyescdl** [comment]
Related PR for Nuxeo processing on batch servers
https://github.com/CDLUC3/mrt-atom/pull/1

**Comment by terrywbrady** [comment]
Linking to https://github.com/CDLUC3/mrt-admin-lambda/pull/56
