### ISSUE TITLE
[Minio/<PROVIDER> checklist] Add <ENV> Storage node

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#108]
Node number is of the form `3PPE` where `3` indicates external storage, `PP` is a two-digit number indicating the provider (e.g. `03` = UCSB), and `E`is the environment: `1` = prod, `2` = stage, `3` = dev.

Configuration files are in the `mrt-conf-prv/s3-conf` private repository, under `src/main/resources/nodes`.

 - [ ] Configure endpoint URL and credentials in minio-<PROVIDER>-<ENV>.properties
 - [ ] Assign node number and add to nodes-ext-<ENV>.properties
 - [ ] Rebuild configuration JAR (Jenkins: mrt-build-s3)
 - [ ] Rebuild Storage service (Jenkins: mrt-store-pub—note not mrt-build-store) to pick up new configuration JAR
 - [ ] Rebuild Audit service (Jenkins: mrt-build-audit) to pick up new configuration JAR
 - [ ] Rebuild Replic service (Jenkins: mrt-build-replic) to pick up new configuration JAR
 - [ ] Update ops page

**Comment by elopatin-uc3** [comment]
Hi @dloy, can you please comment on whether or not this ticket should be closed? It outlines what sounds like Minio migration work that may already be done. Thanks, Eric
