### ISSUE TITLE
[Minio/<PROVIDER> checklist] Configure and redeploy/restart Storage servers in <ENV>

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#109]
1. Make sure you've updated `mrt-conf-prv/s3-conf` and built a new configuration JAR
   (see previous ticket)

2. In the [mrt-store-config](https://github.com/CDLUC3/mrt-store-config) repository:

   - add new node directory under `config/src/<ENV>/repository`
   - add `can-info.txt` file to new node directory
   - add new node directory to `config/src/<ENV>/store/nodes.txt`
   - commit and push changes (`git add . && git commit -m"<summary of changes>" && git push`)
   - create new tag (use `YYYY.MINOR.MICRO` [calendar versioning](https://calver.org/) e.g. `2019.1.2`):' 
     `git tag -a"<version>" -m"<summary of changes>" && git push --tags`
   - redeploy mrt-store-config to the environment: 
     `TAG=<tag> bundle exec cap <env> deploy`

3. For each storage server:

   - redeploy the application to pick up the new configuration JAR and updated
     config files
 - [ ] Add node directory and can-info.txt to mrt-store-config
 - [ ] Record node directory in mrt-store-config nodes.txt
 - [ ] Redeploy mrt-store-config to environment
 - [ ] On each Storage server in this environment, redeploy & restart Storage service to pick up new configuration JAR

**Comment by elopatin-uc3** [comment]
Updated to reflect new [mrt-store-config](https://github.com/cdlib/mrt-store-config/) repository (David Moles - Jan 14, 2019)

**Comment by elopatin-uc3** [comment]
Hi @dloy, can you please comment on whether or not this ticket should be closed? It outlines what sounds like some of the NodeIO table work you've already completed recently for Minio and Wasabi. Thanks, Eric
