### ISSUE TITLE
New collection: UC Berkeley Library Greek Papyri

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1110]
Collection title: UC Berkeley Library Greek Papyri
user: ucblap, ucbroa, davidtriebwasser

#### Tasks: Production
- [x] Create collection intake form
- [ ] Create collection profiles: collection, submission
- [ ] Submit collection admin object
- [ ] Mint collection ARK
- [ ] Add collection to inventory database (introduced via admin object submission after collection profile is live)
- [ ] Set primary storage node (introduced via admin object submission after collection profile is live)
- [ ] Create associated entries in LDAP
- [ ] Update collection record with name, mnemonic, privs
- [ ] Add secondary storage nodes to inv_collections_inv_nodes table (Glacier and Wasabi)
- [ ] In EZID, set collection Status (to unavailable) and Harvesting option (to No)

**Comment by elopatin-uc3** [comment]
Intake form: https://docs.google.com/document/d/1yzHenZ3Hn7HFAxufGY0d1jf71AHqISW2wqIHaN5_ENs/edit#
