### ISSUE TITLE
Document checklist for setting up new collections

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#116]
This should be a ticket or set of tickets that can be cloned to cover all the tasks for creating a new collection:

#### Steps to create a collection
   1. Mint collection ARK
   1. Create collection profile using documentation provided by svcs manager
   1. Add collection to inventory database
   1. Add collection owner, admin objects
   1. Set primary storage node
   1. Create new collection entry in LDAP
   1. Add secondary storage node to inv_collections_inv_nodes table 
   1. Record collection info on Ops page

#### Ingest profile properties to set
   1. ARK
   1. collection ID
   1. primary storage node ID
   1. Record ingest profile in appropriate branch of the [mrt-ingest-profile repo](https://github.com/cdlib/mrt-ingest-profile/) 

Previously recorded steps, for example purposes:
 - Product Mgr Creates documentation (see example in comments)
 - Define Ingest Profile
 - Create ARK and submit system objects via ingest 
 - Update EZID record status to unavailable (see screenshot in comments below) - Manage IDs, set to unavailable and do not harvest
 - Create LDAP record 
 - Update INV inv_collections table - requires access to DB:  fill in missing fields, access is updated, read and download are public - If using mrt-express, collection is restricted. Otherwise, public. Write is always restricted.
 - Add record to INV inv_collections_inv_nodes for SECONDARY storage node/replication

### Tasks (to be copied to subsequent new collection request tickets)
- [x] Create collection documentation
- [x] Create collection profile
- [x] Add collection owner (introduced in collection profile*)
- [x] Mint collection ARK
- [x] [Create associated entries in LDAP](https://confluence.ucop.edu/display/UC3/Adding+Merritt+Collections+and+Users+to+LDAP+using+Apache+Directory+Studio)
- [x] Add collection to inventory database
- [x] Update collection record with name, mnemonic, privs 
- [x] Set primary storage node
- [x] Add secondary storage node**s** to inv_collections_inv_nodes table (Glacier and Wasabi)
- [x] In EZID, set collection Status (to unavailable) and Harvesting option (to No)

**Comment by elopatin-uc3** [comment]
Alternative steps noted in [another Pivotal ticket ](https://www.pivotaltracker.com/story/show/166228455)(for a Dryad collection):

1. Create documentation
1. Create LDAP records
1. Create and submit system objects (Mark)
1. Update EZID record status to Unvavailable
1. Udpate LDAP record
1. Update inv_collections table in Inventory database
1. Add record to inv_collections_inv_nodes for secondary storage node, in Inv db

**Comment by elopatin-uc3** [comment]
Latest steps used for creation of new collections for UCB and UCI, in order:
- Create collection documentation
- Create collection profile
- Add collection owner (introduced in collection profile*)
- Mint collection ARK
- Create associated entries in LDAP
- Add collection to inventory database
- Update collection record with name, mnemonic, privs 
- Set primary storage node
- Add secondary storage nodes to inv_collections_inv_nodes table (Glacier and Wasabi)
- In EZID, set collection Status (to unavailable) and Harvesting option (to No)
