### ISSUE TITLE
New collection: 10 new collections for UC Berkeley Library

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1215]
#### Ten new collections requested:
UC Berkeley Library Bancroft Mark Twain Notebooks
UC Berkeley Library EAL Julean Arnold Snapshots
UC Berkeley Library EAL Ground and Aerial Views of China
UC Berkeley Library Bancroft C. Hart Merriam Papers
UC Berkeley Library Bancroft Land claims in California
UC Berkeley Library DLA Bulletin
UC Berkeley Library 18th-century Italian Music Manuscripts
UC Berkeley Library Koret Southeast Asian Palm-Leaf and Leporello Manuscripts
UC Berkeley Library Bancroft Jesse Brown Cook Scrapbooks
UC Berkeley Library Bancroft George and Phoebe Apperson Hearst papers microfilm

#### Access:
Users: ucblap, ucbroa, dt, DZ
Permissions: r/w/download

#### Tasks: Production
- [x] Create collection intake forms
- [x] Create collection profiles: collection, submission
- [x] Submit collection admin object
- [x] Mint collection ARK
- [x] Add collection to inventory database (introduced via admin object submission after collection profile is live)
- [x] Set primary storage node (introduced via admin object submission after collection profile is live)
- [x] Update collection record with name, mnemonic, privs
- [x] Add secondary storage nodes to inv_collections_inv_nodes table (Glacier and Wasabi)
- [x] In EZID, set collection Status (to unavailable) and Harvesting option (to No)

#### LDAP entries:
- [x] UC Berkeley Library Bancroft Mark Twain Notebooks
- [x] UC Berkeley Library EAL Julean Arnold Snapshots
- [x] UC Berkeley Library EAL Ground and Aerial Views of China
- [x] UC Berkeley Library Bancroft C. Hart Merriam Papers
- [x] UC Berkeley Library Bancroft Land claims in California
- [x] UC Berkeley Library DLA Bulletin
- [x] UC Berkeley Library 18th-century Italian Music Manuscripts
- [x] UC Berkeley Library Koret Southeast Asian Palm-Leaf and Leporello Manuscripts
- [x] UC Berkeley Library Bancroft Jesse Brown Cook Scrapbooks
- [x] UC Berkeley Library Bancroft George and Phoebe Apperson Hearst papers microfilm

**Comment by elopatin-uc3** [comment]
Intake forms complete.
