### ISSUE TITLE
New collection: 9 new collections for UC Berkeley

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1247]
#### Nine new collections requested:
UC Berkeley Library EAL Jiyi Remembrance (MAD)
UC Berkeley Library Humanities ASLA annual meeting proceedings (MAD)
UC Berkeley Library al-masar (MAD)
UC Berkeley Library Humanities funambulist (MAD)
UC Berkeley Library Humanities L'Italo-Americano (MAD)
UC Berkeley Library Humanities mozartfest (MAD)
UC Berkeley Library PlanEcon Report (MAD)
UC Berkeley Library Sciences Renewable resources journal (MAD)
UC Berkeley Library Humanities UCLA Anderson forecast for the nation and California (MAD)

#### Access:
Users: ucblap, ucbroa, dt
Permissions: r/w/download

#### Tasks: Production
- [x] Create collection intake forms
- [x] Create collection profiles: collection, submission
- [x] Submit collection admin object
- [x] Mint collection ARK
- [x] Add collection to inventory database (introduced via admin object submission after collection profile is live)
- [x] Set primary storage node (introduced via admin object submission after collection profile is live)
- [x] Update collection record with name, mnemonic, privs
- [x] Add secondary storage nodes to inv_collections_inv_nodes table (Glacier and Wasabi)
- [x] In EZID, set collection Status (to unavailable) and Harvesting option (to No)

#### LDAP entries:
- [x] UC Berkeley Library EAL Jiyi Remembrance (MAD)
- [x] UC Berkeley Library Humanities ASLA annual meeting proceedings (MAD)
- [x] UC Berkeley Library al-masar (MAD)
- [x] UC Berkeley Library Humanities funambulist (MAD)
- [x] UC Berkeley Library Humanities L'Italo-Americano (MAD)
- [x] UC Berkeley Library Humanities mozartfest (MAD)
- [x] UC Berkeley Library PlanEcon Report (MAD)
- [x] UC Berkeley Library Sciences Renewable resources journal (MAD)
- [x] UC Berkeley Library Humanities UCLA Anderson forecast for the nation and California (MAD)

**Comment by elopatin-uc3** [comment]
Intake forms created; profiles created; all other tasks done for all collections, except for LDAP entries.
