### ISSUE TITLE
Enable testing the full java stack from M2 mac AND from DEV server

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1322]
## Conventions

Dev Server and Jenkins
```
export ECR_REGISTRY=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
```

M2 Mac
```
export ECR_REGISTRY=it-docker-registry
```

## Tasks
_Modify configurations to be runnable on an M2 mac.  Verify functions still work on Server and in Jenkins._

- [x] For M2 compatibility, avoid zookeeper:3 images in pom.xml
- [x] For M2 compatibility, avoid zookeeper:3 images in src/test/docker/docker-compose.yml
- [x] ~Remove smtp from ingest IT stacks AND remove NotificationHandler from IT collection profiles~
  - change the smtp image to one that works on M2 and on server 
- [x] Ensure that every java project has a good src/test/README.md
  - [x] ingest
  - [x] inventory
  - [x] audit
  - [x] replic
  - [x] store 
- Build [IT Stack](https://github.com/CDLUC3/merritt-docker/tree/main/mrt-inttest-services)
  - [x] Server - https://github.com/CDLUC3/merritt-docker/blob/main/bin/it_build.sh
  - [x] M2 mac - https://github.com/CDLUC3/merritt-docker/blob/main/bin/local_it_build.sh
  - [x] Jenkins - http://builds.cdlib.org/job/Docker%20Images%20for%20Integration%20Testing/
- Build [Dev Stack](https://github.com/CDLUC3/merritt-docker/blob/main/mrt-services/docker-compose.yml)
  - [x] Server - https://github.com/CDLUC3/merritt-docker/blob/main/bin/dep_build.sh
  - [x] M2 Mac - https://github.com/CDLUC3/merritt-docker/blob/main/bin/local_dep_build.sh
  - [x] Jenkins - https://github.com/CDLUC3/merritt-docker/blob/main/bin/local_dep_build.sh
- Build Services with Maven and Run IT Tests
  - [x] Server - https://github.com/CDLUC3/merritt-docker/blob/main/bin/maven_build.sh
  - [x] M2 Mac - https://github.com/CDLUC3/merritt-docker/blob/main/bin/local_maven_build.sh
  - [x] Jenkins - http://builds.cdlib.org/job/mrt-core-int-test-all/   
- Run Dev Stack
  - [x] Server 
  - [x] M2 Mac 
    - [ ] Resolve localhost presigned issue 
- Documentation
  - [x] Update documentation to describe server testing
  - [x] Update documentation to describe desktop testing 

## Java Services
_Modify configurations to be runnable on an M2 mac.  Verify functions still work on Server and in Jenkins._

- Cloud
  - [x] Server VSCode JUnit Tests
  - [x] M2 Mac VSCode JUnit Tests
- Ingest
  - [x] Server VSCode JUnit Tests
  - [x] M2 Mac VSCode JUnit Tests
- Inventory
  - [x] Server VSCode JUnit Tests
  - [x] M2 Mac VSCode JUnit Tests
- Storage
  - [x] Server VSCode JUnit Tests
  - [x] M2 Mac VSCode JUnit Tests
- Audit
  - [x] Server VSCode JUnit Tests
  - [x] M2 Mac VSCode JUnit Tests
- Replic
  - [x] Server VSCode JUnit Tests
  - [x] M2 Mac VSCode JUnit Tests

**Comment by elopatin-uc3** [comment]
Closing.
