### ISSUE TITLE
New collections: 7 new collections for UC Berkeley

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1355]
#### Nine new collections requested:
UC Berkeley Library Bancroft Out West
UC Berkeley Library Bancroft Overland Monthly
UC Berkeley Library Bancroft Golden era
UC Berkeley Library Bancroft Pacific school journal
UC Berkeley Library Bancroft Pandex of the press
UC Berkeley Library Bancroft Northern crown
UC Berkeley Library Bancroft Coronado tent city news

#### Access:
Users: ucblap, ucbroa, dt
Permissions: r/w/download

#### Tasks: Production
- [x] Create collection intake forms
- [x] Create collection profiles: collection, submission
- [x] Submit collection admin object
- [x] Mint collection ARK
- [x] Add collection to inventory database (introduced via admin object submission after collection profile is live)
- [x] Set primary storage node (introduced via admin object submission after collection profile is live)
- [x] Update collection record with name, mnemonic, privs
- [x] Add secondary storage nodes to inv_collections_inv_nodes table (Glacier and Wasabi)
- [x] In EZID, set collection Status (to unavailable) and Harvesting option (to No)

#### LDAP entries:
- [x] UC Berkeley Library Bancroft Out West
- [x] UC Berkeley Library Bancroft Overland Monthly
- [x] UC Berkeley Library Bancroft Golden era
- [x] UC Berkeley Library Bancroft Pacific school journal
- [x] UC Berkeley Library Bancroft Pandex of the press
- [x] UC Berkeley Library Bancroft Northern crown
- [x] UC Berkeley Library Bancroft Coronado tent city news
