### ISSUE TITLE
New collections: Four new collections for UCB

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1365]
#### Four new collections requested:
UC Berkeley Library Bancroft The Arrowhead magazine and guide book
UC Berkeley Library Bancroft The Pacific monthly
UC Berkeley Library Bancroft Pacific Presbyterian
UC Berkeley Library Bancroft The California teacher

#### Access:
Users: ucblap, ucbroa, dt
Permissions: r/w/download

#### Tasks: Production
- [x] Create collection intake forms
- [x] Create collection profiles: collection, submission
- [x] Submit collection admin object
- [x] Mint collection ARK
- [x] Add collection to inventory database (introduced via admin object submission after collection profile is live)
- [x] Set primary storage node (introduced via admin object submission after collection profile is live)
- [x] Update collection record with name, mnemonic, privs
- [x] Add secondary storage nodes to inv_collections_inv_nodes table (Glacier and Wasabi)
- [x] In EZID, set collection Status (to unavailable) and Harvesting option (to No)

#### LDAP entries:
- [x] UC Berkeley Library Bancroft The Arrowhead magazine and guide book
- [x] UC Berkeley Library Bancroft The Pacific monthly
- [x] UC Berkeley Library Bancroft Pacific Presbyterian
- [x] UC Berkeley Library Bancroft The California teacher
