### ISSUE TITLE
New collections: Stage and Production UCJEPS collections

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1379]
#### Two new collections:
University and Jepson Herbaria Image Archive - Stage
University and Jepson Herbaria Image Archive - Prod

#### Access:
Users: JB, JA r/w/d

#### Tasks: Stage
- [x] Create collection intake forms
- [x] Create OWNER profile
- [x] Create collection profiles: collection, submission
- [x] Submit collection admin object
- [x] Mint collection ARK
- [x] Add collection to inventory database (introduced via admin object submission after collection profile is live)
- [x] Set primary storage node (introduced via admin object submission after collection profile is live)
- [x] Update collection record with name, mnemonic, privs
- [x] In EZID, set collection Status (to unavailable) and Harvesting option (to No)
- [x] LDAP entries

#### Tasks: Production
- [x] Create collection intake forms
- [ ] Create OWNER profile
- [ ] Create collection profiles: collection, submission
- [ ] Submit collection admin object
- [ ] Mint collection ARK
- [ ] Add collection to inventory database (introduced via admin object submission after collection profile is live)
- [ ] Set primary storage node (introduced via admin object submission after collection profile is live)
- [ ] Update collection record with name, mnemonic, privs
- [ ] Add secondary storage nodes to inv_collections_inv_nodes table (Glacier and Wasabi)
- [ ] In EZID, set collection Status (to unavailable) and Harvesting option (to No)
- [ ] LDAP entries

**Comment by elopatin-uc3** [comment]
See also https://github.com/CDLUC3/mrt-doc/issues/1309
