### ISSUE TITLE
New collection: University and Jepson Herbaria collection, Production

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1410]
#### New collection requested:
University and Jepson Herbaria Collection

#### Access:
Users: jbl, jeps submitter
Permissions: r/w/download

#### Tasks: Production
- [x] Create SLA object
- [x] Create Owner object
- [x] Create Jeps submitter account for production
- [x] Create collection intake forms
- [x] Create collection profiles: collection, submission
- [x] Submit collection admin object
- [x] Mint collection ARK
- [x] Add collection to inventory database (introduced via admin object submission after collection profile is live)
- [x] Set primary storage node (introduced via admin object submission after collection profile is live)
- [x] Update collection record with name, mnemonic, privs
- [x] Add secondary storage nodes to inv_collections_inv_nodes table (Glacier and Wasabi)
- [x] In EZID, set collection Status (to unavailable) and Harvesting option (to No)

#### LDAP entries:
- [x] University and Jepson Herbaria Collection

**Comment by elopatin-uc3** [comment]
Intake form: https://docs.google.com/document/d/1g4O0Y3t9dJvh_AeU_79ePbLAniqOPEKR9M5dlR6WEHY/edit#

**Comment by elopatin-uc3** [comment]
Production callback URL needed.

**Comment by elopatin-uc3** [comment]
Updated callback URL for production.
