### ISSUE TITLE
Daily Build / Docker Build / Trivy Scan Process

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1488]
## Purpose

Build a script to rebuild ALL Merritt docker images on a daily or weekly basis.  Incorporate trivy scan into the build process.

If the solution works well, consider also running maven builds in a similar manner.

To be determined if this should run in Jenkins.

## Background

- Replaces #1245
- Replaces #1241
- https://github.com/CDLUC3/merritt-docker/blob/main/bin/build_scan_all.sh 

## Build Script documentation
- https://github.com/CDLUC3/merritt-docker/blob/main/fresh_build.md

## Team Demo
- [x] Full build/scan - fun in advance: `bin/fresh_build.sh -e`
- [x] Local build: `bin/fresh_build.sh -C main-docker -w $PWD`
- [x] Jenkins - buildall: `bin/fresh_build.sh -j -C main-jenkins -m uc3 -p testall`
- [x] Jenkins - build store: `bin/fresh_build.sh -j -C main-jenkins -m store -p label`
- [x] Jenkins - buildall (newbuild): `bin/fresh_build.sh -j -C newbuild-jenkins -m uc3 -p testall`
  - [x] download audit
  - [x] jar tf WEB-INF/lib/mrt-core* - look for newbuild.core.yml
  - [x] jar tf WEB-INF/lib/mrt-cloudconf* - look for newbuild.cloud.yml
- [x] Jenkins - build ingest (tag: newbuild-tag): `bin/fresh_build.sh -j -C main-jenkins -m ingest -t newbuild-tag`
  - [x] jar tf WEB-INF/lib/mrt-ingestconf* - look for newbuild.yml
- [x] Jenkins - build ingest (branch: newbuild): `bin/fresh_build.sh -C main-jenkins -m ingest -t newbuild`

## TODO
- [x] add flag to enable/disable maven tests
- [x] allow working directory to be passed to the script (or use a default ENV from Jenkins)
- [x] add code to enable/disable directory recreation
- [x] enable script to be run from Jenkins
  - param: branch
  - param: bc_profile
  - pull summary file into build log
  - copy artifacts to content directory
- [ ] create ability to pull built war files to an assemble directory
  - [ ] apply meaningful names to assembled assets
- [ ] create build.content.txt
- [ ] meaningful use of tag name or branch name when building a service  
- [ ] consider an ability to selectively build specific services
  - [x] maven
  - [ ] docker 
- [ ] make use of yaml features to re-use blocks of config 

### Build Execution
- Run script with a named branch of merritt-docker: main
- Run script with a named build-config: main

### Create a Build Configuration Yaml file

```
repositories:
  mrt-core: url
  mrt-cloud: url
  cdl-zk-queue: url
  mrt-zoo: url
  mrt-inventory: url
  mrt-store: url
  mrt-ingest: url
  mrt-audit: url
  mrt-replic: url
  mrt-dashboard: url
build-config:
  main:
    tags:
      mrt-core: main
      mrt-cloud: main
      cdl-zk-queue: main
      mrt-zoo: main
      mrt-inventory: main
      mrt-store: main
      mrt-ingest: main
      mrt-audit: main
      mrt-replic: main
      mrt-dashboard: main
    docker-tag: dev
    push: true
    artifacts-tag: testall
    scan-unfixable: true
    scan-fixable: true
```

## Build Steps

- delete working directory
- clone merritt-docker
- check out branch/tag (parameter: named branch of merritt-docker)
- checkout all submodules
- read build-config for build config (parameter: named build config)
- iterate over repos (yaml repositories)
  - checkout branch for each repo (yaml build-config branches)
- run builds
  - run integ test image builds
  - build microservices
  - build other stack components
  - build auxillary (integ tests)
 - run tests
Output
- build summary report
- build success
- scan success
- date/time since last lambda
- all vulnerabilities
- fixable vulnerabilities

## How to run the script
- Dev box, on demand
- Dev box, by cron
- Jenkins box
