### ISSUE TITLE
New collection: UCR: Eaton Fanzine Collection

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1498]
#### New collection requested:
UC Riverside Library Eaton Fanzine Collection

#### Access:
Users: KB, MB
Permissions: r/w/download

#### Tasks: Production
- [x] Create collection intake forms
- [x] Create collection profiles: collection, submission
- [x] Submit collection admin object
- [x] Mint collection ARK
- [x] Add collection to inventory database (introduced via admin object submission after collection profile is live)
- [x] Set primary storage node (introduced via admin object submission after collection profile is live)
- [x] Update collection record with name, mnemonic, privs
- [x] LDAP entries
- [x] Add secondary storage nodes to inv_collections_inv_nodes table (Glacier and Wasabi)
- [x] In EZID, set collection Status (to unavailable) and Harvesting option (to No)
- [x] Add new account for MB

**Comment by elopatin-uc3** [comment]
Collection intake form created:
https://docs.google.com/document/d/1x7nbH7Hoet-Zum4wrLZdDhl2tMOF557S8ymmjjAv_DE/edit
