### ISSUE TITLE
New Collection: UC Berkeley Law: Robbins Collection

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1542]
#### New collection requested:
UC Berkeley Law: Robbins Collection

#### Access:
Users: EB
Permissions: r/w/download

#### Tasks: Production
- [x] Create collection intake form
- [x] Create SLA and Owner profiles
- [x] Create collection profiles: collection, submission
- [x] Submit collection admin object
- [x] Mint collection ARK
- [x] Add collection to inventory database (introduced via admin object submission after collection profile is live)
- [x] Set primary storage node (introduced via admin object submission after collection profile is live)
- [x] Update collection record with name, mnemonic, privs
- [x] LDAP entries
- [x] Create new account for EB
- [x] Add secondary storage nodes to inv_collections_inv_nodes table (Glacier and Wasabi)
- [x] In EZID, set collection Status (to unavailable) and Harvesting option (to No)

**Comment by elopatin-uc3** [comment]
Intake form: 
https://docs.google.com/document/d/1ROpklnGyhiLxgMQIgX3_ey70rqAOsXYeZuZc679wpvc/edit#heading=h.rgyu7vatyvzr
