### ISSUE TITLE
New collections: CDL Preprints for EarthArXiv and EcoEvoRxiv

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1543]
#### Two new collections requested:
[EarthArXiv](https://eartharxiv.org/)
[EcoEvoRxiv](https://ecoevorxiv.org/)

#### Access:
Users: LS, MY
Permissions: r/w/download

- [x] Create MY production account
- [x] Create CN production account

#### Tasks: EarthArXiv
- [x] Create collection intake forms
- [x] Create collection profiles: collection, submission
- [x] Submit collection admin object
- [x] Mint collection ARK
- [x] Add collection to inventory database (introduced via admin object submission after collection profile is live)
- [x] Set primary storage node (introduced via admin object submission after collection profile is live)
- [x] Update collection record with name, mnemonic, privs
- [x] LDAP entries
- [x] Add secondary storage nodes to inv_collections_inv_nodes table (Glacier and Wasabi)
- [x] In EZID, set collection Status (to unavailable) and Harvesting option (to No)

#### Tasks: EcoEvoRxiv
- [x] Create collection intake forms
- [x] Create collection profiles: collection, submission
- [x] Submit collection admin object
- [x] Mint collection ARK
- [x] Add collection to inventory database (introduced via admin object submission after collection profile is live)
- [x] Set primary storage node (introduced via admin object submission after collection profile is live)
- [x] Update collection record with name, mnemonic, privs
- [x] LDAP entries
- [x] Add secondary storage nodes to inv_collections_inv_nodes table (Glacier and Wasabi)
- [x] In EZID, set collection Status (to unavailable) and Harvesting option (to No)

**Comment by elopatin-uc3** [comment]
Intake forms:
https://docs.google.com/document/d/1lSnoua_3IkcoaFz3W3T1SWwazLePg--JVKEnu7nELy0/edit?usp=sharing
https://docs.google.com/document/d/1vRMH4qtTPzl8hVTALURbEadmznLz6agDP98wLdyp7G8/edit?usp=sharing
