### ISSUE TITLE
New Collection: CDL Dryad Dev 3043

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1585]
#### New collection requested:
cdl_dryaddev_3043

#### Access:
Users: SF, DL
Permissions: r/w/download

#### Tasks: Production
- Create collection intake forms: Not needed
- [x] Create collection profiles: collection, submission
- [x] Submit collection admin object
- [x] Mint collection ARK
- [x] Add collection to inventory database (introduced via admin object submission after collection profile is live)
- [x] Set primary storage node (introduced via admin object submission after collection profile is live)
- [x] Update collection record with name, mnemonic, privs
- [x] LDAP entries
- [x] Add secondary storage nodes to inv_collections_inv_nodes table (Glacier and Wasabi)
- [x] In EZID, set collection Status (to unavailable) and Harvesting option (to No)
