### ISSUE TITLE
Large object and dataset download email event recording recipients change 

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#167]
### Summary 
Since the launch of Dryad, journal editors have expressed dismay about the additional recipients on the `To` line of the large object/dataset email messages being sent. This is due to the fact that the download feature is being used in conjunction with private peer review. The Dryad team has requested that we remove all internal CDL recipients from these messages, however we still need to be able to track that emails were sent successfully, and their content is correct. 

Current recipient configuration for production is found here:
https://github.com/CDLUC3/mrt-dashboard/blob/fb4f92c00e68e5a3af93846959a4aeda1df8f222/config/app_config.yml#L44

Ideas on how to address this issue:
* Remove CDL recipients from the `lostorage_email_to` entry of the product config file.
* Print a copy of of the email to mrt-dashboard `production.log` which includes the URL to the download. 
  * It looks like we have the majority of information about the object to be downloaded in the log already, so perhaps this only involves confirming what's logged now is sufficient as a measure of successful email distribution, without actually sending the final message to CDL recipients.
  * For consideration: We can continue to test email functionality on Stage with CDL recipients.

### Tasks
- [x] Confirm if logging to `production.log` is sufficient for recording email distribution success
- [x] If it is, remove CDL recipients from `app_config.yml`
- [x] If it is not sufficient, brainstorm on a different solution and discuss as a team
- [x] Check into BCC possibility -- support in Storage, plus UI change (bcc config). This should be a good interim solution.
- [ ] update documentation for deploying code https://confluence.ucop.edu/display/UC3/Merritt+UI+Production+Redeploy

**Comment by elopatin-uc3** [comment]
Sample log entry:
`Started GET "/asyncd/ark:%2F13030%2Fm52k1jd7/4?user_agent_email=ryaxley%40datadryad.org&userFriendly=true&lo
sFrom=uc3%40ucop.edu&losSubject=Your+download+for+Urbanization+impacts+apex+predator+gene+flow+but+not+genet
ic+diversity+across+an+urban-rural+divide+is+ready&losBody=The+dataset+that+you+have+requested+is+ready+for+
you+to+download.++Please+follow+the+link%0Abelow+to+download+your+file%3A%0A%0A++%3C%25%3D+%40dl_url+%25%3E%
0A%0APlease+note+that+this+link+will+expire+in+7+days+from+the+date+of+this+email.++The+content+is+stored%0A
as+a+compressed+file+in+the+%22tar.gz%22+format.++For+many+operating+systems%2C+you+can+extract+the%0Afiles+
by+double-clicking+this+archive.++For+Windows+or+other+systems+you+might+require+a+utility%0Asuch+as+7-zip+%
28+see+http%3A%2F%2Fwww.7-zip.org%2F+%29+to+extract+the+files." for 172.30.22.60 at 2019-10-11 05:40:31 -070
0
Processing by LostorageController#direct as */*
  Parameters: {"user_agent_email"=>"ryaxley@datadryad.org", "userFriendly"=>"true", "losFrom"=>"uc3@ucop.edu
", "losSubject"=>"Your download for Urbanization impacts apex predator gene flow but not genetic diversity a
cross an urban-rural divide is ready", "losBody"=>"The dataset that you have requested is ready for you to d
ownload.  Please follow the link\nbelow to download your file:\n\n  <%= @dl_url %>\n\nPlease note that this 
link will expire in 7 days from the date of this email.  The content is stored\nas a compressed file in the 
\"tar.gz\" format.  For many operating systems, you can extract the\nfiles by double-clicking this archive. 
 For Windows or other systems you might require a utility\nsuch as 7-zip ( see http://www.7-zip.org/ ) to ex
tract the files.", "object"=>"ark:/13030/m52k1jd7", "version"=>"4"}
  Rendered inline template (0.4ms)
  Rendered text template (0.0ms)
Completed 200 OK in 149ms (Views: 0.5ms | ActiveRecord: 1.6ms`

**Comment by marisastrong** [comment]
would be great with this ticket to also update the documentation on redeploying the UI code
https://confluence.ucop.edu/display/UC3/Merritt+UI+Production+Redeploy

**Comment by elopatin-uc3** [comment]
@elopatin-uc3 to determine if immediate config change to remove CDL recipients is necessary as an initial way to address this.

**Comment by elopatin-uc3** [comment]
Adding copy from an email that @dloy sent:

-----
Hi Eric
This is the error email sent when some type of error occurred during the async processing. 

As you can see the To list is a bit outdated  - the storage servers need the latest recipients - who would you like to include?

I thought this was handled as BCC - more research is needed.

Thanks
David


-------- Forwarded Message --------
Subject:
Exception: Your download for Data from: An ab initio electronic transport database for inorganic materials is ready
Date:
Tue, 5 Nov 2019 07:42:55 -0800 (PST)
From:
uc3@ucop.edu
To:
yasuyuki.masuda@murata.com, marisa.strong@ucop.edu, david.moles@ucop.edu, perry.willett@ucop.edu, jim.vanderveen@ucop.edu, eric.lopatin@ucop.edu


***Unable to complete this requested action***
Customer service will be notified
___________________________________
The dataset that you have requested is ready for you to download. Please follow the link
below to download your file:

http://merritt.cdlib.org/cloudcontainer/mrtstore1/901258329.tar.gz

Please note that this link will expire in 7 days from the date of this email. The content is stored
as a compressed file in the "tar.gz" format. For many operating systems, you can extract the
files by double-clicking this archive. For Windows or other systems you might require a utility
such as 7-zip ( see http://www.7-zip.org/ ) to extract the files.

**Comment by elopatin-uc3** [comment]
Initial pull request, just to remove inactive recipients from the To list:
https://github.com/CDLUC3/mrt-dashboard/pull/37

**Comment by terrywbrady** [comment]
If we want to use the BCC approach, here is a quick outline of the process I would follow to implement it.

Set bcc field through UI here.

https://github.com/CDLUC3/mrt-dashboard/blob/master/app/controllers/lostorage_controller.rb#L115

If a message object is found, parse the object in storage to determine if a bcc (or cc) field is present in message. 

https://github.com/CDLUC3/mrt-store/blob/master/store-src/src/main/java/org/cdlib/mrt/store/action/AsyncContainerObject.java#L474

Set the BCC recipient using the following line as an example.

https://github.com/CDLUC3/mrt-store/blob/master/store-src/src/main/java/org/cdlib/mrt/store/action/AsyncContainerObject.java#L472

**Comment by terrywbrady** [comment]
- UI PR: 
  - https://github.com/CDLUC3/mrt-dashboard/pull/39
- Storage PR:
  - https://github.com/CDLUC3/mrt-store/pull/1

**Comment by elopatin-uc3** [comment]
Checked off first four tasks in the Summary. After discussion, use of only logging to record emails sent was not considered to be sufficient evidence of mail distribution. The option taken is to bcc a restricted set (two persons) of CDL recipients.
