### ISSUE TITLE
UCSF: Five new NHPRC collections

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1694]
These will each be associated with individual Nuxeo collections for harvesting.

- MSS 86-54 Leona Meyer Beyer Collection
- MSS 83-9 Selma Fraiberg Papers
- MSS 2014-17 Helen Fahl Gofman Papers
- MSS 83-18 Carol Hardgrove Papers
- MSS 89-67 Hulda Evelyn Thelander Papers

Collection intake form: 
https://docs.google.com/document/d/146ZJU2pB8ybsGn0MpK6v6I6QIxbcpiEUwZ5jtrOJZDA/edit?usp=sharing

#### Access:
Users: UCSF A&SC, see intake form
Permissions: r/w/download

#### Ownership task:
- [x] Create new NHPRC Owner object
- [x] New accounts for PTL and LS

#### Tasks for all collections:
- [x] Create collection intake forms
- [x] Create collection profiles: collection, submission
- [x] Submit collection admin object
- [x] Mint collection ARK
- [x] Add collection to inventory database (introduced via admin object submission after collection profile is live)
- [x] Set primary storage node (introduced via admin object submission after collection profile is live)
- [x] Update collection record with name, mnemonic, privs
- [x] LDAP entries
- [x] Add secondary storage nodes to inv_collections_inv_nodes table (Glacier and Wasabi)
- [x] In EZID, set collection Status (to unavailable) and Harvesting option (to No)

**Comment by elopatin-uc3** [comment]
Nuxeo direct deposit ticket submitted: https://help.oac.cdlib.org/a/tickets/130823

Tickets generated for Nuxeo feeds: mrt-doc 1707 - 1711
