### ISSUE TITLE
Prototype alternative method for file location handoff to Express

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#171]
### Summary
When an object contains files numbering in the thousands, the XML manifest generated by Inventory for use by Express becomes very large as well. This can lead to long retrieval times related to reading the manifest into memory for/by Express. A more efficient handoff is needed, as several of these types of transactions can eventually tie up a significant number of Express workers, and lead to service degradation (which may also impact other services such as eScholarship). 

This ticket should be used to prototype a more efficient solution for this transaction.

### Tasks
- [x] Determine possible options for improving the efficiency of said transaction involving both Storage and Express, e.g. use of mySQL and the Inv database.
- [x] Inventory Versions response – Build a prototype and test on Stage with several large dataset objects.
- [ ] Merritt Express – Implement endpoint changes to make use of the new versions response, and test on Stage.

**Comment by terrywbrady** [comment]
I do not know which XML library is used for parsing the manifest.  Would it be useful to explore an alternative library that might be more memory efficient?

**Comment by dloy** [comment]
### Versions Method
The versions response from the inventory server is used by Merritt Express for extracting content directly from one of our storage repositories.

The versions response contains:

- cloud service - containing content
- bucket/container - for the key and data
- key - for returning the content.


The current prod version returns a response specific to a version or an object. If the versions are large (e.g. > 100000 files) the time for the response can be excessive (> 4 minutes).

To generate the versions response for either a content version or object, the service receives a request containing the ark and an optional version number.  The inventory process then:

- Looks up the primary node for the ark in the inv database
- Issues a manifest request to the storage service for that object (ark)
- Returns the manifest.xml from storage
- Converts the returned content into a versions response containing details for accessing any specific file in the object: service type, bucket, key
- Sends response to requester (usually Merritt Express)

To speed up this process, a new method has been added to inventory for versions, that includes an additional filepath: ark/version number/filepath

With the filepath versions processing can be extremely simplified:

- Issue a MySQL request specific to a file
- Build a versions response using the MySQL only response.

This eliminates any need for inputting the manifest.xml from the storage service and then having the inventory service parse this response.

This change is possible because all Merritt Express requests are made specifically at the file level.  Also, the  inv database has all necessary content needed for generating the response.

Timings indicate that for very large objects the response can be reduced from 4-5 minutes to 2 seconds.

### Example
**Request**
`curl http://uc3-mrtinv2-stg.cdlib.org:36121/mrtinv/versions/ark%3A%2F99999%2Ffk4sb4bf6z/0/system%2fmrt-ingest.txt?t=xml`

**Response:**
<?xml version="1.0" encoding="UTF-8"?>
<invv:versionsState xmlns:invv='http://uc3.cdlib.org/ontology/mrt/inv/v'>
    <invv:versions>
        <invv:version>
            <invv:files>
                <invv:vFile>
                    <invv:length>1612</invv:length>
                    <invv:key>ark:/99999/fk4sb4bf6z|5|system/mrt-ingest.txt</invv:key>
                </invv:vFile>
            </invv:files>
            <invv:versionNum>5</invv:versionNum>
            <invv:current>false</invv:current>
            <invv:versionSize>1612</invv:versionSize>
        </invv:version>
    </invv:versions>
    <invv:node>9001</invv:node>
    <invv:reportDate>2019-10-31T09:34:37-07:00</invv:reportDate>
    <invv:objectID>ark:/99999/fk4sb4bf6z</invv:objectID>
    <invv:cloudType>swift</invv:cloudType>
    <invv:currentVersion>7</invv:currentVersion>
    <invv:container>distrib.stage.9001.__017</invv:container>
</invv:versionsState>

**Comment by dloy** [comment]
**cdlsys: ALB re-encoding problem for UTF8 ISSUE=13233 PROJ=2**

Ran into problem when using the inv-aws-stg.cdlib.org ALB:

The ALB:
  inv-aws-stg.cdlib.org
points to the 2 severs:
  uc3-mrtinv2-stg.cdlib.org
  uc3-mrtinv-stg.cdlib.org

We are running tests on the stage inventory service for the "versions"
request.

The working curl for this request is:
curl
http://uc3-mrtinv2-stg.cdlib.org:36121/mrtinv/versions/ark%3A%2F99999%2Ffk4t44zg8m/0/producer%2Futf8%2F%E6%95%B0%E6%8D%AE%E6%8F%90%E5%8F%96%E8%A1%A8%E6%A0%BC5.31.txt?t=xml

Using the ALB fails:
curl
http://inv-aws-stg.cdlib.org:36221/mrtinv/versions/ark%3A%2F99999%2Ffk4t44zg8m/0/producer%2Futf8%2F%E6%95%B0%E6%8D%AE%E6%8F%90%E5%8F%96%E8%A1%A8%E6%A0%BC5.31.txt?t=xml

The unicode for the utf8 following %2Futf8%2F is:
/utf8/数据提取表格5.31.txt

The ALB for stage inventory converts:
%2Futf8%2F%E6%95%B0%E6%8D%AE%E6%8F%90%E5%8F%96%E8%A1%A8%E6%A0%BC5.31.txt
   to (from inventory logs)
%2Futf8%2F%C3%A6%C2%95%C2%B0%C3%A6%C2%8D%C2%AE%C3%A6%C2%8F%C2%90%C3%A5%C2%8F%C2%96%C3%A8%C2%A1%C2%A8%C3%A6%C2%A0%C2%BC5.31.txt?t=xml

Solution:
The problem was identified. The error is a result of a front-end Apache
server being called (port 36221) by ALB. When the ALB was modified to
use port 36121 (directly to inventory) both inv servers successfully
completed. When the 36221 was used on a specific server (Apache
front-end) the request failed. Apache is the problem.

Joe modified ALB to use the inv servers directly and updated the
healthcheck for those servers. The remaining task is on Merritt side to
determine what should be done with the Apache front-end.

As Joe indicated, this currently is a problem on prod.

After discussions with Mark, we concluded that the calling inventory directly from the ALB was the best solution. At some point the Apache server on the inv machines could be removed but it should not be called.
