### ISSUE TITLE
Investigate use of S3 pre-signed URLs for hand-off to Dryad for large dataset files (async)

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#172]
### Summary
In order to successfully provide downloads for large files, Dryad currently uses Merritt Express and then sends these through the Dryad UI to an end user. Due to an internal problem with Passenger, the Dryad UI can't stream the file directly. Instead, a workaround has been implemented where Passenger reads the stream by chunks, then writes to a temp file and streams this file out to the user. This operation requires use of two threads, and thus far has been successful, but is not ideal.

For individual files, it would be it would be much simpler to use an S3 “pre-signed URL”. The Dryad UI could redirect to this URL, which would then provide temporary access for a user to download directly from S3.

#### NB
Use of S3 pre-signed URLs would tie us to using native S3 functionality for downloads of large files. This is questionable from two standpoints:
1. With the exception of the Dryad private collection, all other private collection primary nodes will be Minio (Dryad's is S3); which means that initially, we'll be building functionality that is specific to one client and collection.
2. Also, we have yet to find out if any similar functionality exists in Minio.

#### Reference
Doc from initial meeting about this work:
https://docs.google.com/document/d/1Z5G8zHqgUg-0rJIGHpKviNYI9j3rGuOn-HBE_KjkZ7k/edit?usp=sharing

### Tasks
- [ ] Determine if Merritt Express could make a call to S3 and hand the pre-signed URL to Dryad.
- [ ] If feasible, implement a prototype that provides this functionality.
- [ ] Scope out what would be involved with providing a more generic endpoint, e.g. getTemporaryUrl, that would service each primary node storage type and provide a download URL.

**Comment by elopatin-uc3** [comment]
Relates to https://github.com/CDLUC3/mrt-doc/issues/202

**Comment by elopatin-uc3** [comment]
Addressed in pre-signed URL implementation; duplicate. Closing
