### ISSUE TITLE
Additional Wasabi storage testing  

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#173]
### Summary
Initial object handling and timing tests for Wasabi storage were done as part of [ticket 141](https://github.com/CDLUC3/mrt-doc/issues/141). In order build confidence with Wasabi's ability to handle a variety of Unicode characters in object keys, it would be beneficial to set up replication of specific collections to a sandbox. This was originally suggested by @dloy .

### Tasks
- [x] Arrange for additional trial time and sandbox with Wasabi (@elopatin-uc3 )
- [x] Based on recently completed migration to Minio, enumerate a list of collections to replicate; specifically, those that have objects considered to be high-risk in terms of keys, content, and size.
- [x] Set up and trigger replication for these collections to the Wasabi sandbox.
- [x] Evaluate and report on replication test outcomes.

**Comment by dloy** [comment]
Storage service on sandbox2-stg is now running and can direct content to the wasabi east2 region (us-east-2). Because of 1 T limitation I am currently submitting content as storage copy (technique used by replication but without normal replication configurations. The size of objects being submitted runs between 50G and 100G. The test tomcat is running on a 1/2T temp area.

**Comment by elopatin-uc3** [comment]
Per David, the testing executed here cannot account for data longevity. In other words, our trials were limited to one month time spans. On a related note, during tests for Minio at SDSC, the team was able to audit objects after a 3-month time period to confirm all was well after a slightly greater timeframe.
