### ISSUE TITLE
Release: Merritt UI and Storage updates

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#175]
### Tasks
- [x] Deploy mrt-dashboard – Merritt UI
- [x] Deploy mrt-store – Merritt Store
- [x] Validation upon deployment

#### Services:
mrt-dashboard – Merritt UI
mrt-store – Merritt Store

#### Servers:
Stage:
uc3-mrtui01-stg.cdlib.org
uc3-mrtui02-stg.cdlib.org
uc3-mrtstore-stg.cdlib.org
uc3-mrtstore2-stg.cdlib.org
Production:
uc3-mrtui01-prd.cdlib.org
uc3-mrtui02-prd.cdlib.org
uc3-mrtui03-prd.cdlib.org
uc3-mrtstore1-prd.cdlib.org
uc3-mrtstore2-prd.cdlib.org

#### Change description
- Email recipient changes for large object and dataset downloads.
- Travis build configuration changes for mrt-dashboard.

#### Infrastructure Changes to support software (ALB, EFS, etc) 
CDL-SYS ticket submitted:
- Modification to production ALB, inv-aws.cdlib.org

#### Travis:
[build name/number]
https://travis-ci.org/CDLUC3/mrt-dashboard

#### Github Issues:
https://github.com/CDLUC3/mrt-doc/issues/166
https://github.com/CDLUC3/mrt-doc/issues/167
https://github.com/CDLUC3/mrt-doc/issues/184

#### Source Code:
mrt-dashboard:
https://github.com/CDLUC3/mrt-dashboard/pull/37
https://github.com/CDLUC3/mrt-dashboard/pull/39

mrt-store:
https://github.com/CDLUC3/mrt-store/pull/1

**Comment by mreyescdl** [comment]
Merged to master branch and deployed to both Stage workers.
Please test

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl . I just received an email for the download of the following object:
ark:/99999/fk4p56t73p

Sorry not to have tested this already. I will see if perhaps David kicked off the above test.

**Comment by elopatin-uc3** [comment]
Two large object download tests on Stage both returned emails with the correct, revised recipients.
Screen shots from one of these requests attached:

![Screen Shot 2019-11-19 at 1 42 01 PM](https://user-images.githubusercontent.com/49419424/69189010-79bc1280-0ad2-11ea-9c3d-005ba4784a42.png)
![Screen Shot 2019-11-19 at 1 27 41 PM](https://user-images.githubusercontent.com/49419424/69189011-79bc1280-0ad2-11ea-95a9-fa6c59bb8127.png)

**Comment by elopatin-uc3** [comment]
Moving to Ready to Deploy.

**Comment by dloy** [comment]
## Redeploy production servers
uc3-mrtstore-prd.cdlib.org

uc3-mrtstore2-prd.cdlib.org

### Source code changes
Github: bcc changes and merge: https://github.com/CDLUC3/mrt-store/commit/a81f377e613d66e607ed0a9f6188e1289781a48e

### Jenkins Build
http://builds.cdlib.org/job/mrt-build-store/96/console

http://builds.cdlib.org/job/mrt-store-pub/104/console

Prod Storage update 191205-10:45-11:15

**Comment by mreyescdl** [comment]
Production UI redeployed to bring in changes.

**Comment by elopatin-uc3** [comment]
Verifying in production now, with a large dataset download from Dryad, as well as a large object download directly from the Merritt UI.

**Comment by elopatin-uc3** [comment]
Both look good. Also confirmed with BCC recipient (@marisastrong):
![Screen Shot 2019-12-05 at 3 17 28 PM](https://user-images.githubusercontent.com/49419424/70283128-01617c80-1775-11ea-8a4c-bab8367a6e95.png)
![Screen Shot 2019-12-05 at 3 17 54 PM](https://user-images.githubusercontent.com/49419424/70283129-01617c80-1775-11ea-8283-d7354f71b89c.png)

**Comment by elopatin-uc3** [comment]
We discovered that Dryad has it's own email template that is somehow related to Storage for async downloads: https://github.com/CDL-Dryad/dryad-app/blob/e8f48bfa9841ba92a68f840785edc24964c97c69/stash/stash_engine/app/views/stash_engine/downloads/async_email.txt.erb 

I will file a ticket with Dryad to request removal of the "7 day" notice.
