### ISSUE TITLE
Limit number of object files displayed in UI for performance reasons

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#182]
### Summary
Recently a request from UCI resulted in an effort to extract a small number of images from a very large object, which contains over 200K files. Simply attempting to browse this object caused extreme memory conditions on a the EC2 instance. Though the host had 8GB of memory allocated, it quickly used up nearly all swap available and became unresponsive.

In cases like these, we should make an effort to limit the number of files displayed when browsing the object. If possible, pagination could be a solution, where each new page causes a list of (e.g.) 200 file links to be displayed.

### Tasks
- [ ] PM/dev/UX to work on determining an appropriate UX 
- [ ] Determine conditions under which pagination would be required
- [ ] Prototype a solution and test on Stage
- [ ] Implement, test, deploy final solution
