### ISSUE TITLE
UCSF Vintage Theses & Dissertations – initial batch

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#199]
### Summary
The Merritt team is working with Publishing & Special Collections to ingest UCSF "vintage" theses and dissertations (VTDs) dating back to the 1970-80s. As part of this effort, MY will be handling scans of these from Google. Said scans will include metadata and OCR data. Metadata will be cherrypicked to generate a ProQuest XML metadata file for each, which will then coupled with a PDF. We plan to ingest an initial batch of these into Merritt via use of batch manifests. Once the first batch has been successfully harvested into eScholarship, remaining batches will follow.

### Tasks
- [x] Using Stage UCSF ETDs collection in Merritt, test an initial VTD and validate handling of PDF and XML
- [x] Mahjabeen to create a batch manifest with the initial set of VTDs to ingest.
- [x] Ingest this set into the UCSF ETDs collection on Merritt Stage (via UI submission of manifest)
- [x] Manually run eSchol harvester to move these into eSchol stage
- [x] Distribute QA tasks to evaluate a series of VTDs on Merritt and eSchol stage
- [x] Ingest same set into production and harvest
- [x] Spot checks of content in production

**Comment by elopatin-uc3** [comment]
@terrywbrady this is an ongoing effort by eScholarship. I've updated the summary to reflect completed tasks. We just ingested another small set of 10 VTDs onto stage with corrections suggested by UCSF. Soon these will all go to production. I'll move this onto the board under Content.
