### ISSUE TITLE
Release – Merritt UI change for Open Context

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#208]
Release – Merritt UI change for Open Context

### Tasks
While making use of the load balancer, deploy changes to these hosts, in turn: 
- [x] uc3-mrtui01-prd.cdlib.org  
- [x] uc3-mrtui02-prd.cdlib.org
- [x] uc3-mrtui03-prd.cdlib.org

Services:
mrt-dashboard – Merritt UI

Servers:
Production:
uc3-mrtui01-prd.cdlib.org
uc3-mrtui02-prd.cdlib.org
uc3-mrtui03-prd.cdlib.org

Change description
For guest login to the Merritt UI, Rails redirects traffic to the login controller over http, rather than https. This shouldn't be the case for any login action (guest or no).

Infrastructure Changes to support software (ALB, EFS, etc)
N/A

Issue trackers:
https://github.com/CDLUC3/mrt-doc/issues/128

**Comment by elopatin-uc3** [comment]
Released briefly on 2020-01-16 on one UI host and tested with the Open Context site. Changes released appeared to addressed one part of the issue related to collection choice, but it did not address the initial login redirect. We are also cognizant of additional javascript code Open Context has introduced to mitigate the original issue, and will be discussing this with them in the next few days.

**Comment by terrywbrady** [comment]
Changes deployed Jan 30, 2020

**Comment by terrywbrady** [comment]
@elopatin-uc3 , what follow up is needed for the Safari issue?
