### ISSUE TITLE
UCSB ETDs workflow changes

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#211]
### Summary
UCSB would like ProQuest to deliver their ETDs directly to CDL's SFTP server under the ProQuest (PQ) account there. This ticket encompasses all the tasks related to the requested workflow change.

### Tasks
- [x] Preliminary tests on ETDs Stage to determine `getetds.py` behavior when checking campus codes and scanning the `proquest` folder on the `sftp` server.
- [x] Update `campus.yml` with new PQ SFTP account entry for UCSB config
```
    sftp_user: ucsbetd <<< change to proquest
    sftp_retrieve_dir: ucsbetd <<< change to proquest
    sftp_delivery_dir: None
```
- [x] Scope and implement changes to `getetds.py` script
- [x] Update `app_config.yml` with PQ SFTP account entry for UCSB config (line 63)
```
sftpETDdirs:
    proquest: proquest
    ucla: uclaetd/etds
    ucsb: ucsbetd <<< change to proquest
```

**Comment by elopatin-uc3** [comment]
Note that the `app_config.yml` change is required in Puppet repo.

**Comment by elopatin-uc3** [comment]
Still waiting on successful transmission of test file from ProQuest to CDL SFTP.

**Comment by elopatin-uc3** [comment]
ProQuest successfully delivered a test file to the `/proquest` directory, under the proquest account on our SFTP server for the UCSB workflow. Interestingly, I have only seen other UCLA ETDs come through for processing (these are delivered to the uclaetd account. I haven't seen other campus ETDs come through via the proquest account. Once I do see one come through, I will mark this ticket as done, to indicate existing production workflows have not been affectec.

**Comment by elopatin-uc3** [comment]
Several ETDs have been processed from UCSF and UCSD, both of which use the proquest account on the SFTP server. Here is a downstream record of ETDs harvested by eScholarship:
`Harvesting UC Berkeley ETDS.
ucb collection done: 0 new, 0 changed, 7985 same, 0 errors
Harvesting UC Irvine ETDS.
uci collection done: 0 new, 0 changed, 3181 same, 0 errors
Harvesting UCLA ETDS.
ucla collection done: 59 new, 0 changed, 8060 same, 0 errors
Harvesting UC Merced Library ETDS.
ucm collection done: 0 new, 0 changed, 593 same, 0 errors
Harvesting UCR ETDS.
ucr collection done: 0 new, 0 changed, 3527 same, 0 errors
Harvesting UCSC ETDS.
ucsc collection done: 0 new, 0 changed, 1751 same, 0 errors
Harvesting UCSD ETDS.
ucsd collection done: 10 new, 0 changed, 9506 same, 0 errors
Harvesting UC San Francisco ETDS.
ucsf collection done: 51 new, 0 changed, 2081 same, 0 errors
Harvesting UC Santa Barbara ETDS.
ucsb collection done: 0 new, 0 changed, 1731 same, 0 errors
Done.`

**Comment by elopatin-uc3** [comment]
Moving to Done
