### ISSUE TITLE
Investigate load-balanced Storage and Inventory timing issue as it relates to Minio

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#218]
### Summary
After flipping all restricted access collections to use Minio/Qumulo as primary node storage, we are observing an issue where the use of two, load-balanced Storage servers is prohibiting a handshake between Storage and Inventory.

### Tasks
- [ ] Attempt to reproduce the issue on Stage
- [ ] Root cause timing issues if possible
- [ ] Bring SDSC into the loop when we have evidence of the problem to discuss

**Comment by elopatin-uc3** [comment]
Attaching David's sync error observations:
[sync-error.txt](https://github.com/CDLUC3/mrt-doc/files/4106354/sync-error.txt)

**Comment by terrywbrady** [comment]
## Python test driver
Terry created the following repo and has run it from multiple hosts at one time.  So far, this has not reproduced the problem.

- [ ] Check if auto-resubmit is occurring within the S3 calls (Terry)
- [ ] Compare the file size in the object metadata with the file size of the downloaded object (Terry)

## Other tasks
- [ ] Reconfirm that there is not a thread timing issue in which the manifest is written before sub-object file writes are completed (David)
- [ ] Document a description of the issue and send it to SDSC (David)

**Comment by terrywbrady** [comment]
I re-ran my tests and I am still unable to produce an error when retrieving an S3 object.  

@dloy , I recommend we close this issue once you verify the one pending item above.

**Comment by elopatin-uc3** [comment]
SDSC has commented/requested for us to wait until additional system (Minio) changes to take place on their side. They may chase this down post-upgrade.

With the current implementation, we may be suppressing evidence of the issue per retries. However we can monitor this via the retry messages that are now in logs.
