### ISSUE TITLE
Endpoint and credentials changes for Minio Update at SDSC

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#229]
### Summary
From Gavin B. at SDSC:
SDSC has started a project to implement a more robust erasure coding scheme on the Qumulo cluster that will provide better data protection and support future growth. Downtime will be needed to cutover the storage. 
 
I’ve already copied the data to the new EC stripe and I have a replication job that runs continuously. However, the replication currently needs about 4 hours to process the changes received from the MinIO gateway and S3 clients. I think the simplest cutover would be to establish the new MinIO environment with the new EC stripe (e.g. accessible from cdl.s3.sdsc.edu) then schedule a time in which we can set the current environment (i.e. cdl.qs3.sdsc.edu) read-only allowing us to perform a final transfer to mirror the data. Once the transfer completes, the application would need to update the S3 endpoint to cdl.s3.sdsc.edu. 

From David:
Changing the endpoint will require redeploys  for our servers (storage, replications and audit) to point to the new end point for Minio:

From:
cdl.qs3.sdsc.edu
To:
cdl.s3.sdsc.edu

Any change to a cloud store requires a modification to our NodeIO tables that is brought in statically as part of a rebuild.
### Steps
The following tasks attempt to minimize the down time of Merritt to be as close as possible to the mirroring time at SDSC for the last completed update to the new server from add content on the original server.

Additionally, the updated storage will support presign-file method, also, storage access to Wasabi.

- Modify stage and prod  storage before transition to run all  nodes using new nodeIO tables with the exception of the Minio nodes
- At time of transition, modify Minio nodes to use new nodeIO table, followed by restart
- Redeploy of audit, and replic to use new nodeIO tables

#### Pre-endpoint changes
These steps occur before Storage uses the the new service endPoint. These changes will allow Storage to be restarted at the time of the actual transition without requiring a redeployment at that time. 

Update of NodeIO tables
- [x] Creating NodeIO tables that include the new server endPoint  Minio entry: 
nodes-stage.properties, nodes-prod.properties.
- [x] [Update of github mrt-conf-prv/s3-conf repository](https://github.com/cdlib/mrt-conf-prv/tree/master/s3-conf/src/main/resources/nodes)
- [x] [Build of configuration jar using Jenkins - mrt-build-s3](http://builds.cdlib.org/job/mrt-build-s3/)

Add presign-file method
- [x] See Implement the presign-file endpoint in the Storage Service #236

Redeploy of Stage Storage servers
- [x] Build new stage war files containing the updated NodeIO tables
- [x] For non-minio nodes, modify the can-info.txt to use the new NodeIO tables. Keep all Minio node can-info.txt tables using the old NodeIO tables
- [x] Add Wasabi node for node 2002: /dpr2/repository/node2002Wasabi
- [x] Redeploy stage storage

Redeploy of Prod Storage servers
- [x] Build new prod war files containing the updated NodeIO tables
- [x] For non-minio nodes, modify the can-info.txt to use the new NodeIO tables. Keep all Minio node can-info.txt tables using the old NodeIO tables
- [x] Add Wasabi node for node 2001: /dpr2/repository/node2002Wasabi
- [x] Redeploy prod storage

#### Endpoint transition Stage
This phase occurs during and after the endpoint transition at SDSC. The time needed by this step is dependent on the final mirroring of content from the old SDSC Minio to the new SDSC Minio.

Goal: nothing on Stage is accessing old minio server

- [x] (Mark) 24 hours before scheduled stage and prod storage shutdown monitors audit, replic
- [x] (David) 24 hours before scheduled stage and prod storage shutdown auxiliary services using Minio - audit, replic 
- [x] (David) Shutdown stage and prod storage - done before SDSC mirroring
- [x] (Mark) Freeze Stage ingest 24 hours?
- [x] (Mark) Turn off Nuxeo harvesting for Stage

SDSC Begins mirroring and  transition

- [x] (David) Modify Stage NodeIO tables in Minio can-info.txt (nodes tables)
- [x] (David) _Modify Stage NodeIO tables in store-info.txt_
- [x] (David) Modify Stage NodeIO tables in audit-info.txt for all audit servers
- [x] (David) Modify Stage NodeIO tables in replic-info.txt for all replic servers

#### Endpoint transition Prod
This phase occurs during and after the endpoint transition at SDSC. The time needed by this step is dependent on the final mirroring of content from the old SDSC Minio to the new SDSC Minio.

Goal: nothing on Prod is accessing old minio server

- [x] (Mark) 24 hours before scheduled storage shutdown monitors audit, replic
- [x] (David) 24 hours before scheduled storage shutdown auxiliary services using Minio - audit, replic 
- [x] (David) Shutdown storage - done before SDSC mirroring
- [x] (Mark) Freeze Prod ingest 24 hours?

SDSC Begins mirroring and  transition

- [x] (David) Modify NodeIO tables in Minio can-info.txt (nodes tables)
- [x] (David) _Modify NodeIO tables in store-info.txt_
- [x] (David) Modify NodeIO tables in audit-info.txt for all audit servers
- [x] (David) Modify NodeIO tables in replic-info.txt for all replic servers

### SDSC Completes transition
- [x] (David) Restart Stage Storage
- [x] (David) Restart Prod Storage
- [x] ?? (Mark) Restart Storage monitors

#### After Transition for storage
Because both audit and replic do not have immediate dependencies from other micro-services their restart is not time critical

- [x] (David) Restart Audit
- [x] (David) Restart Replic
- [x] (Mark) Restart monitors

#### Notes
MerrittExpress is not impacted by endpoint change - all content is AWS
? Stage flip

- Redeploy the stage/prod servers to include the new NodeIO table. This will confirm that the non-Minio nodes are operating
### Tasks
- [ ] Investigate the possibility of implementing a dynamic config and credential update process, rather than having them tied to the actual build process. 
- [x] Coordinate with SDSC on proposed downtime.
- [ ] Determine test strategy
- [x] Document procedures for switchover to new endpoint and review with team.
- [x] Switchover – likely in a separate ticket w/procedures

**Comment by dloy** [comment]
From Gavin: 1/31/2020, 8:17 P.M.
* How long will the old system be up after your initial mirroring? If it will, would there be any attempts at synchronizing the content after the initial mirror?

The initial mirror has already completed, but the replication feature we’re leveraging is asynchronous and the delta transfers are taking a few hours to complete each run. I’ll let you know next week how much time we’re able to save on the delta transfers after we add some tuning.


* Can we get working credentials for the new cdl.s3.sdsc.edu? It will be important to confirm access to this service. This would hopefully eliminate problems on the conversion.

Currently we use: serviceType, endPoint, accessKey and secretKey

We can use the same credentials for cdl.s3.sdsc.edu or we can establish new keys – whatever is easier for you. The ‘target’ storage is readonly while the replication relationship is established. I haven’t attempted to bring up a minIO instances on a read-only backend but I suspect it may not be possible as the backend is used to store various system data along with user data. I can test this next week and run through a mock cutover. That said, I can always provision the instances with a temporary backend and allow you to confirm the environment although the only difference to the client will be the round-robin DNS entry that points to the two active load balancers – the S3 interfaces and MinIO will operate the same.

* Are you planning to set the read-only on the old environment for the full time of the transfer or in a shorter time window specific to the final transfer to mirror data?

I’ll confirm if the ‘old’ environment can be left online in a read-only state during the cutover, but we’d only be impacted during the final transfer to mirror the source and target.

 
Next steps are with me – I’ll confirm whether MinIO can run with a read-only backend, and how much progress we can make on optimizing the delta transfers.

**Comment by dloy** [comment]
## Stage Detail
### Servers:
- uc3-mrtstore-stg
- uc3-mrtstore2-stg

### Stop
- [ ] /apps/dpr2store/bin/capStoreStop

### Reset
- [ ] /apps/dpr2store/mrtHomes/store/store-info.txt
signedNodeName=nodes-stg-store
archiveNodeName=nodes-stg-store
 __becomes__
signedNodeName=nodes-stage
archiveNodeName=nodes-stage

- [ ] /apps/dpr2store/repository/node4101UNM/can-info.txt
logicalVolume: nodes-stg-store|4101
 __becomes__
logicalVolume: nodes-stage|4101

- [ ] /apps/dpr2store/repository/node9502SDSCMinio/can-info.txt
logicalVolume:  nodes-stg-store|9502
 __becomes__
logicalVolume:  nodes-stage|9502

### Restart
- [ ]  /apps/dpr2store/bin/capStoreStart

**Comment by dloy** [comment]
## Prod Detail
### Servers:
- uc3-mrtstore1-prd
- uc3-mrtstore2-prd

### Stop
- [ ] /apps/dpr2store/bin/capStoreStop

### Reset
- [ ] /apps/dpr2store/mrtHomes/store/store-info.txt
signedNodeName=nodes-prd-store
archiveNodeName=nodes-prd-store
 __becomes__
signedNodeName=nodes-prod
archiveNodeName=nodes-prod

- [ ] /apps/dpr2store/repository/node9501Minio/can-info.txt
logicalVolume: nodes-prd-store|9501
 __becomes__
logicalVolume: nodes-prod|9501

### Restart
- [ ]  /apps/dpr2store/bin/capStoreStart
