### ISSUE TITLE
Check in scripts from crontab on Inv01

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#240]
### Summary
A series of scripts are run on Inventory worker 01, under the dpr2 role account's crontab. These should be documented and checked into a repo.

### Tasks
- [ ] Determine if the repo should be private, per contents of the scripts
- [ ] Create a new public or private repo, e.g. mrt-billing-perf-scripts and check them in
- [ ] Document their existence on the Merritt Operations confluence page (see #307)

**Comment by terrywbrady** [comment]
Batch server has been created
