### ISSUE TITLE
Add Wasabi test collection on Stage

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#259]
### Summary
Though Wasabi storage is currently intended as a secondary node, we should set up a collection on stage that includes Wasabi storage as a primary node, for testing purposes.

### Tasks
- [x] Create a collection on Merritt stage named Wasabi Demo
- [x] The collection's primary node should be 2002 (Wasabi) 
- [x] Create collection documentation
- [x] Create collection profile
- [x] Add collection owner (introduced in collection profile*)
- [x] Mint collection ARK
- [x] Add collection to inventory database
- [x] Update collection record with name, mnemonic, privs
- [x] Set primary storage node
- [x] Create associated entries in LDAP
- [x] In EZID, set collection Status (to unavailable) and Harvesting option (to No)

Not needed for this collection:
- Add secondary storage node to inv_collections_inv_nodes table 

*Ownership object ARK introduced in collection profile. Content ownership confirmation in the inventory database can only occur after objects have been added to the collection.

**Comment by elopatin-uc3** [comment]
[New_collection_template.docx](https://github.com/CDLUC3/mrt-doc/files/4362193/New_collection_template.docx)

See also #116

**Comment by elopatin-uc3** [comment]
Collection documentation for review:
[Wasabi_demo.docx](https://github.com/CDLUC3/mrt-doc/files/4371913/Wasabi_demo.docx)

**Comment by mreyescdl** [comment]
Hi @elopatin-uc3 

How about renaming the collection to "cdl_wasabi"
This is consistent with our other internal collections, e.g. "cdl_minio"

**Comment by elopatin-uc3** [comment]
Thanks, sounds good @mreyescdl . Let's go with "cdl_wasabi"

**Comment by mreyescdl** [comment]
@elopatin-uc3 
The collection object has been created and the collection profile is available.
Can you add the following to Stage LDAP?

group ID: ark:/13030/m5bp594s
profile ID: cdl_wasabi_content

**Comment by elopatin-uc3** [comment]
@mreyescdl LDAP entries for the Wasabi collection are now complete on Stage.

**Comment by elopatin-uc3** [comment]
All tasks completed. Note I did not add a secondary storage node for this collection.

Tested adding an object: https://merritt-stage.cdlib.org/m/ark%253A%252F99999%252Ffk4tq7842d
