### ISSUE TITLE
Wasabi replication kick-off

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#268]
### Summary
We will be replicating the majority of content in Merritt to Wasabi, which will provide us with a second auditable (a third overall) copy of our collections. This ticket records initial steps (beyond bucket and node creation) to kick off this migration.

### Tasks
- [x] Update Minio migration reporting scripts to report metrics on content copied to Wasabi us-east-2
- [x] Outline overall migration steps (in this ticket)
- [x] Test migration on Stage, TBD
- [x] Trigger the migration of a subset of collections in production, and monitor
