### ISSUE TITLE
Enable viewing of UC Merced PPDC collection content

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#269]
### Summary 
While taking snapshots of inventory for campuses, I've run across a series of UC Merced collections that appear to have content, but are not displayed in the Merritt UI. These collections are under the UC Merced Admin owner. 

Emily Lin, at UCM Library has informed me that these collections were created by the UCM PPDC:
https://policies.ucmerced.edu/Physical_Planning_Design_and_Construction

Byte counts can be found in `uc3-mrtinv01x2-prd:/dpr2/bin/merritt_billing/exempt-coll.csv`
and are listed as exempt content.

### Tasks
- [ ] Determine if collection configuration is correct
- [ ] Determine if the content of `exempt-coll.csv` is accurate
- [ ] Attempt to make these collections available in the UI

**Comment by elopatin-uc3** [comment]
[exempt-coll_csv.txt](https://github.com/CDLUC3/mrt-doc/files/4331062/exempt-coll_csv.txt)

**Comment by terrywbrady** [comment]
@elopatin-uc3 - status?

**Comment by elopatin-uc3** [comment]
To my knowledge, these collections were never completely established. Closing but will re-open if UCM requests.
