### ISSUE TITLE
MIME type testing for pre-signed URL implementation

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#275]
### Summary
mime type handling has now been implemented for individual file downloads.

### Tasks
- [x] Obtain a list of mime types, one each for Merritt stage and production (216 in stage, 226 in prod)
  - [x] PDF
  - [x] JPEG
  - [x] TIFF
  - [x] PNG
  - [x] XML
  - [x] Word
  - [x] CSV
  - [x] MP4
  - [x] MPEG
  - [x] ZIP
  - [ ] X-WAV
  - [ ] Quicktime
  - [x] RTF
  - [x] HTML
  - [x] JSON
- [x] Determine sample files for each of the mime types we're familiar with, in terms of expected UX
- [x] Check that these are handled as expected in a browser, and/or after each file has been downloaded
- [ ] For key types, explicitly test in major browsers
  - [x] Chrome
  - [x] Firefox
  - [x] Safari
  - [ ] IE/Edge
- [ ] File Size - confirm behavior for a file > 5G
- [ ] Verify Wasabi tests

**Comment by elopatin-uc3** [comment]
[stage_mimetype.xlsx](https://github.com/CDLUC3/mrt-doc/files/4361131/stage_mimetype.xlsx)
[merritt_mimetypes_2020-03-03.xlsx](https://github.com/CDLUC3/mrt-doc/files/4361134/merritt_mimetypes_2020-03-03.xlsx)

**Comment by elopatin-uc3** [comment]
- [PDF](https://merritt-stage.cdlib.org/m/ark%253A%252F99999%252Ffk4t72pn0m) UCLA ETDs collection
  - JPEG
  - TIFF
  - [TXT](https://merritt-stage.cdlib.org/m/ark%253A%252F99999%252Ffk4z03df3t) UCLA ETDs collection
  - PNG
  - [XML](https://merritt-stage.cdlib.org/m/ark%253A%252F99999%252Ffk41z4dh3h) UCLA ETDs collection
  - Word
  - CSV
  - MP4
  - MPEG
  - ZIP
  - X-WAV
  - Quicktime
  - RTF
  - HTML
  - JSON
- File Size - confirm behavior for a file > 5G

**Comment by elopatin-uc3** [comment]
@terrywbrady I was able to find objects which include all of the above file types, with the exception of Quicktime. Note that I added M4A, which downloads as a .mov file on a mac via Chrome. This was the only odd behavior I observed while finding sample files. 

I attempted to create a new 5+GB file to upload, but ran into a limit of 4GB for TIFFs in Photoshop. We'll need to find a sample file for this case.

Also, I'll set up access for you to the collections called out above.

**Comment by elopatin-uc3** [comment]
Okay, you should now have access to all of the collections where sample objects are located on stage @terrywbrady

**Comment by terrywbrady** [comment]
Thanks @elopatin-uc3 , this will be helpful for this effort and for future efforts.

I will do some testing in Chrome, Firefox and Safari.  

@dloy , could you spot check a few mime types in IE?

**Comment by terrywbrady** [comment]
@dloy , here is a link to a 6G file.  Is this sufficient for our test?  https://merritt-stage.cdlib.org/m/ark%253A%252F99999%252Ffk4kw5kc1z/1
