### ISSUE TITLE
Examine request stats from Storage and UI logs

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#276]
### Summary
In order to uncover stats related to large object downloads (e.g. object downloads, file downloads, object/version size, and processing time), examine a snapshot of Storage and UI logs.

Ultimately, this will help us gain some insight into possible costs surrounding use of presigned URLs, and the associated object storage use during their window of expiration.

### Prototype Code
- https://github.com/terrywbrady/mrt-log-analyzer

### Tasks
- [ ] Storage Logs
  - [x] Parse logs
  - [x] Report requests by request type
  - [x] Report average request size by type
  - [ ] Report average request time
  - [x] Produce CSV file
  - [ ] Add Date/Time to CSV
  - [ ] Add IP address to CSV
- Storage Configuration
   - [ ] Can tomcat be configured to report request duration?
 - [ ] UI Logs
  - [x] Parse logs
  - [x] Report request by type
  - [ ] Correlate UI request and storage requests to identify timings
  - [ ] Correlate requests with other apache logs (load balancer) to identify timings 
- Other timing options
  - [ ] Explicitly time/curl tests of a known size object retrieval through UI + Storage
  - [ ] Embed a unique request token in every request sent to storage to enable the results to be correlated
  - [ ] Explore Google Analytics options for counting downloads - can this track timings?
- Statistics Analysis
  - [ ] Custom program
  - [ ] Explore log analysis tools such as Splunk
  - [ ] Save CSV to S3 + Athena
  - [ ] Explore Google Analytics options

**Comment by terrywbrady** [comment]
https://github.com/terrywbrady/mrt-log-analyzer/blob/master/log-analyzer.py

```
Highly Requested Arks
=====================
                 Key: Num Requests         Average Size
ark%3A%2F13030%2Fm5zd32c3   134
ark%3A%2F13030%2Fm57x1dx9   108
ark%3A%2F13030%2Fm5r2635n    92
ark%3A%2F13030%2Fm54j5fjk    84
ark%3A%2F13030%2Fm5450spt    80
ark%3A%2F13030%2Fm5tn2b25    66
ark%3A%2F13030%2Fm5b32vk7    64
ark%3A%2F13030%2Fm5wx2kcg    60
ark%3A%2F13030%2Fm5gn38z8    52
ark%3A%2F13030%2Fm59938q4    38
ark%3A%2F13030%2Fm5kx0hzq    36
ark%3A%2F13030%2Fm5wx2gt2    34
ark%3A%2F13030%2Fm50w3cm3    32
ark%3A%2F13030%2Fm54z0705    26
ark%3A%2F13030%2Fm5hq929j    24
ark%3A%2F13030%2Fm5jb18bz    22
ark%3A%2F13030%2Fm5m95gz9    22
ark%3A%2F13030%2Fm5ns5x99    20
ark%3A%2F13030%2Fm54n43pw    20
ark%3A%2F13030%2Fm51c6zp9    20

Storage Requests
================
   total-records req:    121,811                  0.0
            file req:     87,122             44,961.5
        manifest req:     13,267             66,579.6
            post req:     12,615              2,678.0
           state req:      5,052              1,476.9
   dryad-version req:      3,445         39,533,571.3
  cloudcontainer req:        210      2,188,581,712.7
 produce-version req:         96         44,575,918.0
         version req:          2            274,025.0
          object req:          2             60,142.0

UI Requests
================
              view-object-page:    107,556
                   guest-login:     58,520
                 download-file:     24,323
                object-request:     12,562
             choose-collection:      2,400
                 async-request:      2,389
                     u-request:      2,187
                  misc-request:        239
            collection-request:        182
                    dm-request:        171
                asyncd-request:        134
                 object-ingest:        120
            word-press-request:        106
                     s-request:         68
                         login:         37
            download-object **:         36
             view-version-page:         29
                 object-update:          6
           download-version **:          4
                lostorage-page:          1

```

Note that the UI files are archived weekly and the storage files are archived daily, so it is a bit more challenging to synchronize the 2 sets of files.

I recommend that we run some explicit timing of object/version requests of various sizes to determine a good time estimate for our anticipated time frames.

**Comment by terrywbrady** [comment]
## Requests from 3/1 to 3/25 mid day

```
Highly Requested Arks
=====================
                           Ark: Num Requests 
           ark:/13030/m5wb0h94       1053
           ark:/13030/m5pg6zsk        804
           ark:/13030/m5f52w7s        524
           ark:/13030/m5b32vk7        514
           ark:/13030/m5r2635n        149
           ark:/13030/m5nc7fc1        141
           ark:/13030/m5256hnq        140
           ark:/13030/m5zd32c3        134
           ark:/13030/m52c0c61        133
           ark:/13030/m50w3cm3        129
           ark:/13030/m5ns5x99        124
           ark:/13030/m5rg125g        124
         ark:/13030/qt8490b3kt        122
           ark:/13030/m5g216wx        120
         ark:/13030/qt8b42c320        116
           ark:/13030/m56h9qk4        115
           ark:/13030/m5f81kdz        114
           ark:/13030/m5jq677w        112
           ark:/13030/m54z0705        112
           ark:/13030/m5hq929j        111
           ark:/13030/m5ht7w5z        108

Storage Requests
=====================
   total-records req:    718,792                  0.0
     system-file req:    297,699                790.1
   producer-file req:    226,944          3,654,645.9
            post req:     75,848              2,663.8
        manifest req:     75,665             49,870.4
           state req:     21,196              1,586.9
   dryad-version req:     19,512         39,008,036.5
  cloudcontainer req:      1,067      3,415,954,889.8
 produce-version req:        696         71,731,452.0
   delete-object req:         82              6,994.6
    presign-file req:         58                927.2
          object req:         14          2,850,535.3
         version req:         11            575,717.4
```

**Comment by terrywbrady** [comment]
Re-running for a 50 day period.

```
Highly Requested Arks
=====================
                           Ark: Num Requests 
           ark:/13030/m5b61jb1       1159
           ark:/13030/m5wb0h94       1057
           ark:/13030/m5b32vk7        843
           ark:/13030/m5pg6zsk        804
           ark:/13030/m51p31c2        715
           ark:/13030/m5f52w7s        524
           ark:/13030/m58h3t03        404
           ark:/13030/m5bp52bk        347
             ark:/b6071/z7wc73        314

Storage Requests
=====================
   total-records req:  1,123,780                  0.0
     system-file req:    407,315                910.9
   producer-file req:    406,146          2,118,723.8
        manifest req:    105,491             57,324.3
            post req:    102,466              2,854.1
           state req:     43,750              1,564.3
   dryad-version req:     38,965         40,561,033.8
    presign-file req:     15,730              1,683.0
  cloudcontainer req:      2,352      3,073,158,597.5
 produce-version req:      1,435         82,759,622.3
   delete-object req:         82              6,994.6
          object req:         36          3,698,363.8
         version req:         12          1,980,002.3

Requests by Date
=====================
                DATE:       REQS   PRESIGNS                BYTES
          2020-03-01:     21,754          0     42,683,827,967.0
          2020-03-02:     46,994          0    232,462,068,146.0
          2020-03-03:     62,358          1    287,744,798,341.0
          2020-03-04:     52,351          0    170,110,482,020.0
          2020-03-05:     54,112          0    443,026,504,492.0
          2020-03-06:     29,871          0    107,579,771,234.0
          2020-03-07:     18,595          0    108,982,026,713.0
          2020-03-08:     11,330          0     31,165,265,150.0
          2020-03-09:     17,289          0    446,275,996,905.0
          2020-03-10:     14,855         47    285,858,341,397.0
          2020-03-11:     27,840          6    216,348,874,796.0
          2020-03-12:     12,742          2    308,596,415,408.0
          2020-03-13:     17,656          1    352,749,297,713.0
          2020-03-14:     48,753          0    185,072,617,540.0
          2020-03-15:     43,325          0     76,700,457,713.0
          2020-03-16:     45,420          0    254,074,079,278.0
          2020-03-17:     21,255          0    182,486,564,970.0
          2020-03-18:     15,896          0    174,539,303,650.0
          2020-03-19:     12,658          1    465,615,818,912.0
          2020-03-20:     25,290          0    147,704,064,669.0
          2020-03-21:     43,070          0     44,874,791,194.0
          2020-03-22:     30,331          0     90,825,468,627.0
          2020-03-23:     15,362          0    187,398,544,810.0
          2020-03-24:     20,558          0    360,578,703,379.0
          2020-03-25:     11,768          0    117,622,470,161.0
          2020-03-26:     12,438          0    112,420,030,196.0
          2020-03-27:     18,446          0    218,202,320,386.0
          2020-03-28:     28,769          0    125,274,332,765.0
          2020-03-29:     14,271          0     80,927,583,633.0
          2020-03-30:     10,085          0    228,396,134,371.0
          2020-03-31:     15,493          8    123,013,228,988.0
          2020-04-01:      8,818         38    177,707,243,410.0
          2020-04-02:      9,953        263    184,822,374,140.0
          2020-04-03:     11,905        278    155,960,677,449.0
          2020-04-04:     21,432        734     68,287,493,278.0
          2020-04-05:     10,024        704    104,038,667,460.0
          2020-04-06:     13,838        442    162,341,357,395.0
          2020-04-07:     13,315        619    113,117,371,551.0
          2020-04-08:     12,395        342    141,867,734,969.0
          2020-04-09:     13,952        325    189,918,231,556.0
          2020-04-10:     21,732        467    102,024,040,221.0
          2020-04-11:     28,448        518     97,108,207,362.0
          2020-04-12:      8,930        722    106,761,688,880.0
          2020-04-13:     11,029      1,180    131,258,195,609.0
          2020-04-14:     18,498      1,231    304,871,163,098.0
          2020-04-15:     12,704      1,330    349,798,874,486.0
          2020-04-16:     13,433      1,746    253,372,965,506.0
          2020-04-17:     13,774      1,721    471,442,765,158.0
          2020-04-18:     36,172      1,080    172,372,050,315.0
          2020-04-19:      9,704        808    147,032,361,244.0
          2020-04-20:     12,789      1,116    151,350,380,383.0
```

**Comment by terrywbrady** [comment]
Execution notes here: https://github.com/terrywbrady/mrt-log-analyzer/blob/master/README.md

**Comment by elopatin-uc3** [comment]
Thanks @terrywbrady
