### ISSUE TITLE
Prototype UI Changes for Merritt Object / Version Downloads

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#277]
## Prototype Implementation: 
- http://uc3-mrtdocker2-stg.cdlib.org:8089/downloads

## Wireframe Updates
- https://6vxe00.axshare.com/#id=f7fxxc&p=object_landing_page_v2&hi=1&g=1

## TODO's
- [ ] Add object title
- [ ] Add owner/collection information
- [ ] Meet with Rachel's team to review
- [ ] Review the UI approach with Dryad
