### ISSUE TITLE
Create "Fonoroff Lobby Cards" collection for UCB

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#300]
### Summary
Create "Fonoroff Lobby Cards" collection for UCB in production

- "ucbroa" account needs read and download access
- David Triebwasser needs read/write/download access

### Tasks
- [x] Create collection documentation
- [x] Create collection profile
- [x] Add collection owner (introduced in collection profile*)
- [x] Mint collection ARK
- [x] Create associated entries in LDAP
- [x] Add collection to inventory database
- [x] Update collection record with name, mnemonic, privs 
- [x] Set primary storage node
- [x] Add secondary storage nodes to inv_collections_inv_nodes table (Glacier and Wasabi)
- [x] In EZID, set collection Status (to unavailable) and Harvesting option (to No)

*Ownership object ARK introduced in collection profile. Content ownership confirmation in the inventory database can only occur after objects have been added to the collection.

**Comment by elopatin-uc3** [comment]
[UCB_Fonoroff.docx](https://github.com/CDLUC3/mrt-doc/files/4601954/UCB_Fonoroff.docx)

**Comment by elopatin-uc3** [comment]
[UCB_Fonoroff.docx](https://github.com/CDLUC3/mrt-doc/files/4637194/UCB_Fonoroff.docx)

**Comment by mreyescdl** [comment]
@elopatin-uc3 
Can you confirm the primary storage node?
I see both 9502 and 9501 in the word doc. Thanks

**Comment by mreyescdl** [comment]
@elopatin-uc3 
Please add to production LDAP

profile_id: ucb_fonoroff_content
group id: ark:/13030/m51z9c26

**Comment by elopatin-uc3** [comment]
@mreyescdl LDAP entries for this collection have been made in production.

**Comment by elopatin-uc3** [comment]
Inv database update completed:
`UPDATE `inv`.`inv_collections` SET `name` = 'UCB Library Fonoroff Cards Collection', `mnemonic` = 'ucb_fonoroff', `read_privilege` = 'restricted', `write_privilege` = 'restricted', `download_privilege` = 'restricted', `storage_tier` = 'standard' WHERE (`id` = '422');`

**Comment by elopatin-uc3** [comment]
Added two nodes for replication to the `inv_collections_inv_nodes` table. One for Glacier, and another for Wasabi:

`Set up replication (secondary node) to Glacier (13):
insert into inv_collections_inv_nodes
set inv_collection_id=422, inv_node_id=13

Set up replication (tertiary node) to Wasabi (17):
insert into inv_collections_inv_nodes
set inv_collection_id=422, inv_node_id=17`

**Comment by elopatin-uc3** [comment]
All tasks complete; moving to Done.
