### ISSUE TITLE
Update macro in merrittManifest.xls to prevent fileSize and encoding errors during processing

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#305]
### Summary
While working with David Triebwasser at UCB, we ran across an issue with the macro in merrittManifest.xls used to generate .checkm files. He suggested the following edit, which uses a VBA different function to work around the invalid file size error encountered. 

We've also run into an issue with encoding. Even if a .csv is saved using `utf-8` encoding, the macro will convert it to `ansi`. We need to preserve the utf-8 encoding to support characters that are not in `ansi`, such as accented characters.

This stackoverflow post suggests using an optional character set argument that may preserve utf-8 encoding on file open: https://stackoverflow.com/questions/45301892/convert-utf-8-to-ansi-using-vba

NB: The merrittManifest.xls file is the primary method we provide a manifest creation example on the Merritt wiki here: https://github.com/CDLUC3/mrt-doc/wiki/Manifests

### Tasks
- [ ] Update the macros in merrittManifest.xls to address the invalid file size error
- [ ] Investigate the possibility of negating the need to make the first line of .csv files bold. This is currently a requirement so that the macros disregard the first line column labels in .csv's
- [ ] Update macros to support opening .csv files using utf-8 encoding  
- [ ] Post to Merritt wiki

Reference:
https://docs.microsoft.com/en-us/office/vba/language/concepts/getting-started/type-conversion-functions

Suggested edits:
```
Sub ProcessFileSize(row As Range)
    'COM and CBM: Process file size (optional; must be positive integer)
    Dim cellText As String
    cellText = Trim(row.Cells(ColumnIndex:=4))
    
    If cellText <> "" Then
        'Dim size As Long
         ' need something to handle larger file sizes...
         Dim size As Double
        size = 0
        'If there's a conversion error, just leave it set to 0
        On Error Resume Next
            'size = CLng(cellText)
             size = CDbl(cellText)
        On Error GoTo 0
        If size < 1 Then
            errorList = errorList & "Invalid file size " & cellText & " on row " & row.row & vbCrLf
        End If
    End If
    rowText = rowText & cellText & " | "

End Sub

```

**Comment by terrywbrady** [comment]
Manifest Validation Tool replaces
