### ISSUE TITLE
Create "Indochina Archives" collection for UCB

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#311]
### Summary
Create "Indochina Archives" collection for UCB in production

- "ucbroa" account needs read and download access
- David Triebwasser needs read/write/download access

### Tasks
- [x] Create collection documentation
- [x] Create collection profile
- [X] Add collection owner (introduced in collection profile*)
- [x] Mint collection ARK
- [x] Create associated entries in LDAP
- [x] Add collection to inventory database
- [x] Update collection record with name, mnemonic, privs 
- [x] Set primary storage node
- [x] Add secondary storage nodes to inv_collections_inv_nodes table (Glacier and Wasabi)
- [x] In EZID, set collection Status (to unavailable) and Harvesting option (to No)

*Ownership object ARK introduced in collection profile. Content ownership confirmation in the inventory database can only occur after objects have been added to the collection.

**Comment by elopatin-uc3** [comment]
[UCB_Indochina_Archives.docx](https://github.com/CDLUC3/mrt-doc/files/4601956/UCB_Indochina_Archives.docx)

**Comment by mreyescdl** [comment]
@elopatin-uc3 
Please add to production LDAP

profile ID: ucb_indochina_archives_content
group ID: ark:/13030/m59d2521

**Comment by elopatin-uc3** [comment]
@mreyescdl Sorry about not properly specifying the production primary storage node. It should be 9501 (minio, prod) for both of the UCB collections. I'll upload a new copy of the Word document shortly.

**Comment by elopatin-uc3** [comment]
[UCB_Indochina_Archives.docx](https://github.com/CDLUC3/mrt-doc/files/4637191/UCB_Indochina_Archives.docx)

**Comment by mreyescdl** [comment]
@elopatin-uc3 
Thanks Eric.  I guessed right and both collections are now ready for LDAP work

**Comment by elopatin-uc3** [comment]
@mreyescdl Thanks!

**Comment by elopatin-uc3** [comment]
@mreyescdl LDAP entries have been created for this collection in production.

**Comment by elopatin-uc3** [comment]
Inv database update completed:
`UPDATE `inv`.`inv_collections` SET `name` = 'UCB Library Indochina Archives Collection', `mnemonic` = 'ucb_indochina_archives', `read_privilege` = 'restricted', `write_privilege` = 'restricted', `download_privilege` = 'restricted', `storage_tier` = 'standard' WHERE (`id` = '421');`

**Comment by elopatin-uc3** [comment]
Added two nodes for replication to the `inv_collections_inv_nodes` table. One for Glacier, and another for Wasabi:

Set up replication (secondary node) to Glacier (13):
insert into inv_collections_inv_nodes
set inv_collection_id=421, inv_node_id=13

Set up replication (tertiary node) to Wasabi (17):
insert into inv_collections_inv_nodes
set inv_collection_id=421, inv_node_id=17

**Comment by elopatin-uc3** [comment]
All tasks complete; moving to Done.
