### ISSUE TITLE
Scope and prototype automated collection creation

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#328]
### Summary 
Creating a new collection in Merritt requires several steps, including:
Creating new collection profiles, establishing the collection ARK, adding a series of entries to LDAP, and making changes to the Inventory database directly for collection attributes and replication nodes. These tasks are prone to human error and should be automated where possible.

Associated notes in confluence, with more on requirements and current procedures:
https://confluence.ucop.edu/display/~elopatin/Notes+on+automating+collection+creation

### High-level Requirements for a Prototype
Ideally, creating a collection will be an operation we can provide a self-service web form for, presented via the Merritt UI. Use of such a form would be restricted to a specific set of campus-based and CDL users, and allow for generating a collection and specifying user access to it.

However, in the near term, the process of creating a new collection should be made available through a similar web form in the Merritt admin application; of which a prototype currently exists. 

This form should present fields for entry of:
- Collection name
- Collection description
- Selection of an ownership entity (from a drop down menu)
- Notifications

While also introducing entry fields for:

- Collection mnemonic
- Primary and secondary storage nodes
- User account access (e.g. specify user names and associate these with levels of access, such as R/W/D/A)

Provided information will kick off a number of processes that result in:

- Collection profile creation and check in to github
- Minting a collection ARK
- Submission of an initial file to create the collection administrative object
- LDAP entries for the collection and for providing existing users with access to it
- Database entries for collection description and node usage, possibly through new API endpoints provided by the Storage service
- EZID collection status is set, via use of the EZID API.

Given there are numerous operations to be completed, these should become modular in nature, with the ability to leverage modules of functionality through either a command line interface to begin with, and then eventual implementation through Lambda functions and an Amazon API gateway.

### Tasks
- [ ] Using the steps and information noted above, prototype, e.g. command line modules, that could automate common collection creation operations. 
- [ ] Note which operations have dependencies on additional implementation and scope in other microservices. 
- [ ] Associate use of these modules with a web form in the existing Admin tool application.
- [ ] Explore authentication processes for EZID functionality and user log in for creating collections

**Comment by elopatin-uc3** [comment]
Noting currently required steps for setting up a collection:
- Create collection documentation
- Create collection profile
- Add collection owner (introduced in collection profile*)
- Mint collection ARK
- Create associated entries in LDAP
- Add collection to inventory database
- Update collection record with name, mnemonic, privs
- Set primary storage node
- Add secondary storage nodes to inv_collections_inv_nodes table (Glacier and Wasabi)
- In EZID, set collection Status (to unavailable) and Harvesting option (to No)

**Comment by mreyescdl** [comment]
Started work on the collection build process
https://github.com/CDLUC3/mrt-admin-collection

**Comment by terrywbrady** [comment]
@elopatin-uc3 , closing as obsolete
