### ISSUE TITLE
Document the process to alter the primary node for a series of collections from S3 to Minio

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#338]
### Summary
A series of 44 collections that are owned by CDL and campuses continue to use S3 as their primary storage node. The total storage capacity used by these collections as of March 2020 is 5.6TB. For the purpose of cost savings and simplification, the majority of these collections should be reconfigured to use Minio as a primary storage node, with Glacier and Wasabi as secondary nodes.

### Tasks
- [ ] Document the overall steps required for reconfiguring these collections, leveraging methodology used during the Minio migration where possible.
- [ ] Determine feasibility of blocking new ingests on a per-collection basis, to enable collection reconfiguration.
- [ ] Work with @elopatin-uc3 to determine which collections will be excepted, and may stay with S3 as primary.
- [ ] Spin off new tickets for associated work.

**Comment by elopatin-uc3** [comment]
From Scott: " these are the non-Dryad collections we have configured in our application from the old Dash."

dataone.yml:    endpoint: "http://mrtsword.cdlib.org:39001/mrtsword/collection/dataone_dash"
lbnl.yml:    endpoint: "http://mrtsword.cdlib.org:39001/mrtsword/collection/lbnl_dash"
ucb.yml:    endpoint: "http://mrtsword.cdlib.org:39001/mrtsword/collection/ucb_dash"
ucd.yml:    endpoint: "http://mrtsword.cdlib.org:39001/mrtsword/collection/ucd_lib_dash"
uci.yml:    endpoint: "http://mrtsword.cdlib.org:39001/mrtsword/collection/uci_dash"
ucla.yml:    endpoint: "http://mrtsword.cdlib.org:39001/mrtsword/collection/ucla_dash"
ucm.yml:    endpoint: "http://mrtsword.cdlib.org:39001/mrtsword/collection/ucm_dash"
ucop.yml:    endpoint: "http://mrtsword.cdlib.org:39001/mrtsword/collection/ucop_dash"
(not enabled) ucpress.yml:    endpoint: "http://mrtsword.cdlib.org:39001/mrtsword/collection/ucpress_dash"
ucr.yml:    endpoint: "http://mrtsword.cdlib.org:39001/mrtsword/collection/ucr_lib_dash"
ucsb.yml:    endpoint: "http://mrtsword.cdlib.org:39001/mrtsword/collection/ucsb_dash"
ucsc.yml:    endpoint: "http://mrtsword.cdlib.org:39001/mrtsword/collection/ucsc_dash"
ucsf.yml:    endpoint: "http://mrtsword.cdlib.org:39001/mrtsword/collection/ucsf_lib_datashare"

**Comment by elopatin-uc3** [comment]
@dloy I've updated this ticket with ARK information for all DASH collections. Once a procedure is documented, these are the collections to start replication to Dryad first, followed by flipping the primary node.

**Comment by elopatin-uc3** [comment]
@dloy Scott confirmed with Daniella that the UCOP and UC Press Dash collections should be treated the same as all of the others; no differences in terms of replication or migration.

**Comment by elopatin-uc3** [comment]
Related to #482

**Comment by elopatin-uc3** [comment]
Moving this off the project board and back to the Merritt Futures board, for when we begin dealing with the other collections that have their primary object copies in S3.
