### ISSUE TITLE
Create new UCI collections which reflect collecting areas in Nuxeo

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#344]
### Summary
UCI would like to set up new feeds to new Merritt collections, based on their collecting areas in Nuxeo. This ticket encompasses collection setup. A separate ticket will record creating new feed scripts.

### Tasks
Create the following collections:
- [x] UC Irvine SCA Critical Theory Archives
- [x] UC Irvine SCA Southeast Asian Archives
- [x] UC Irvine SCA Special Collections
- [x] UC Irvine SCA University Archives

#### Subtasks for each collection
- [x] Create collection documentation
- [x] Create collection profile
- [x] Add collection owner (introduced in collection profile*)
- [x] Mint collection ARK
- [x] Submit collection object
- [x] Create associated entries in LDAP
- [x] Add collection to inventory database
- [x] Update collection record with name, mnemonic, privs 
- [x] Set primary storage node
- [x] Add secondary storage nodes to inv_collections_inv_nodes table (Glacier and Wasabi)
- [x] In EZID, set collection Status (to unavailable) and Harvesting option (to No)

**Comment by elopatin-uc3** [comment]
Working on collection documentation.

**Comment by elopatin-uc3** [comment]
Documentation complete:

UC Irvine SCA Critical Theory Archives
https://docs.google.com/document/d/1QASkea2kzMzD6vuY7FIouN8XWm43WRpafxLj5enbT9A/edit?usp=sharing

UC Irvine SCA Southeast Asian Archives
https://docs.google.com/document/d/1wbcRFLACPldWtT0-QnuQlQk6UA9fVURkaAw2BdkmBu4/edit?usp=sharing

UC Irvine SCA Special Collections
https://docs.google.com/document/d/1KHGBJgjwU3_mi8D3-DjvpiXe-7VT5dWuqgE08lUs3k4/edit?usp=sharing

UC Irvine SCA University Archives
https://docs.google.com/document/d/1h5bz2nnPO0vtma4GqSJD1OkmQDg7Q57Voc1gfcgQ3oY/edit?usp=sharing

**Comment by elopatin-uc3** [comment]
@mreyescdl Please have a look at the above collection docs. I've installed the dependencies mentioned in your new admin collection repo https://github.com/CDLUC3/mrt-admin-collection. It would be great to walk through this and get everything set up on my laptop, in order to be able to create new collection profiles. Maybe sometime tomorrow (7/10)?

**Comment by mreyescdl** [comment]
@elopatin-uc3 Sure Eric.  Also, I'm creating the EZID minting script today

**Comment by elopatin-uc3** [comment]
@mreyescdl Found a bug in `createProfile.py`. Regardless of which profile is being generated, it checks in its output into the /admin/production/collection folder of the repo. I'll see if I can add a couple of command line args to specify which folder to check a profile file into.

**Comment by elopatin-uc3** [comment]
Done with all collection profiles.

**Comment by mreyescdl** [comment]
I'll submit the collection objects.

**Comment by elopatin-uc3** [comment]
Thanks. I started a local branch with command line arguments (w/argparse), but can't add it to the repo. I'm not sure this is correct approach, as you're already using `sys.argv`. Also wanted to ask how `templateType` is defined.

**Comment by elopatin-uc3** [comment]
Had to correct description entries in two profiles, and just pushed these to the production branch.

**Comment by elopatin-uc3** [comment]
LDAP entries complete for all collections.

**Comment by mreyescdl** [comment]
Collection objects created

http://storage.cdlib.org:35121/state/9501/ark%3A%2F13030%2Fm5159rbd
http://storage.cdlib.org:35121/state/9501/ark%3A%2F13030%2Fm5m95n2q
http://storage.cdlib.org:35121/state/9501/ark%3A%2F13030%2Fm5gb7gff
http://storage.cdlib.org:35121/state/9501/ark%3A%2F13030%2Fm5bk6qsm

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl. It looks like the submission for ark:/13030/m5159rbd didn't go through?

**Comment by elopatin-uc3** [comment]
Mark, David and I were on slack. David was able to process m5159rbd into inventory.
