### ISSUE TITLE
UI notifier error - URI errors and Presigned Download Error

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#380]
I have started to look at a couple of the timeout errors reported from the UI.  The timeout errors are occurring at the point where the call is made to the storage service.  I have not been able to find a matching record of the request on the storage side.
I want to create a table of when the errors occurred over the past week.  I want to compare the error times to other factors in Librato.
Here are some options that I could explore...
- Determine if the old download process had better error handling for calls to storage and replicate that error handling. 
- Verify/increase the timeouts for requests.
- Implement automated retries of timed out requests.
@sfisher, would your rails experience recommend one of these approaches over the others?

sfisher  5:10 PM
IDK exactly what will work best in this case.
I think increasing timeouts may not be a huge help if it's a call you expect should return quickly.
At least in our case having too many long requests (if in the UI) filled our workers.
But puma may be different.
I might try 1 and 3 before 2

terrywbrady  5:13 PM
Thanks.  Do you remember timeout errors occurring in the old download process?

sfisher  5:14 PM
Well, we never so much had a status process.
But some downloads (not async ones) took up to a couple minutes to start.
I'd try to get more information aabout the specific errors you're seeing in all the services to the extent possible.
And rails logging isn't the easiest to read.  :confused:

sfisher  5:29 PM
Or maybe if you can't get a response from the storage service quickly you should just default to a status of "not ready yet"?

terrywbrady  5:31 PM
These errors occurred on both the assemble request and on the get by token request, so the handling might need to be a bit different for each.

## Analysis of requests

- Fri 7/3 4:50AM  to 5:52AM UTC (21:50PT)- 32 errors
- Fri 7/3 1:11AM to 2:47AM UT (18:11PT) 16 errors
  - This appears to be around the time our burst credits were impacted
  - There were also some significant IO events in the storage service at the start of this window
- Th 7/2 - 5 errors

https://confluence.ucop.edu/display/~tbrady/Presigned+Timeout+Error

## TODOs
- [x] Improve error handing in the UI service
  - I really like Scott's suggestion for the get by token requests
- Question: do we need an additional storage service running until we get queuing in place?  We seem to have events on a regular basis.  
  - [x] Discuss this with @marisastrong and @elopatin-uc3 
- Can we identify any other event (such as a big ingest) that started the cascade of events around 18:00 on 7/2?
- [x] Test the error handling within the Merritt + Dryad configuration
  - presigned file needs ui:9292.  other code needs a public url.  Create a public url (other than localhost) that can be accessed in or outside the container
  - [x] Create custom tenant/dryad.yml for ec2
  - [x] Create localhost alias when testing

**Comment by sfisher** [comment]
Hi Terry.  If it's helpful to you to see when we get errors I can extract the timeouts we see from our logs.  IDK if you have ssh access to our servers, but if so I could also give you the grep command and you could grep for the errors whenever you wanted to see when they occurred.

Right now we have our timeout set to 30 seconds since we originally expected the async calls to be a lot faster so we moved our timeout to a much lower setting.  We could also move it back up to a larger setting in our http client.

**Comment by terrywbrady** [comment]
@sfisher , I am using the default timeout values for HTTPClient which I think are set to 1 min and/or 2 min.  Let me know what values you would like me to use.  Since you are the primary user of these api calls, I am happy to tune them to your expectations.

The async requests should be faster, but the solution for that is much larger than can be addressed immediately.  In the interim, I will work to improve error handling.

See https://github.com/CDLUC3/mrt-dashboard/pull/70
- For the assembly task, I will return a 408 when there is a timeout.
- For the get by token task, I will return a 202 when there is a timeout.  (I liked your suggestion)

I am still trying to get my docker instance of Dryad working again so that we can test the timeout behavior between the 2 apps.  I will let you know tomorrow if I am successful.
