### ISSUE TITLE
Create Palestinian Museum collection for UCLA – Stage and Production

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#398]
Set up a new collection for the UCLA Pal Museum project, to house new content from the Palestinian Museum when it arrives.

#### Tasks: Stage
- [x] Create collection documentation
- [x] Mint collection ARK
- [x] Mint owner ARK
- [x] Create collection profiles
- [x] Add collection owner object (introduced in collection profile*)
- [x] Submit collection object
- [x] Create associated entries in LDAP
- [x] Add collection to inventory database
- [x] Update collection record with name, mnemonic, privs 
- [x] Set primary storage node (introduced in collection profile)
- [x] Add secondary storage nodes to inv_collections_inv_nodes table
- [x] In EZID, set collection Status (to unavailable) and Harvesting option (to No)

#### Tasks: Production
- [x] Create collection documentation
- [x] Mint collection ARK
- [x] Mint owner ARK
- [x] Create collection profiles
- [x] Add collection owner object (introduced in collection profile*)
- [x] Submit collection object
- [x] Create associated entries in LDAP
- [x] Add collection to inventory database
- [x] Update collection record with name, mnemonic, privs 
- [x] Set primary storage node (introduced in collection profile)
- [x] Add secondary storage nodes to inv_collections_inv_nodes table (Glacier and Wasabi)
- [x] In EZID, set collection Status (to unavailable) and Harvesting option (to No)

**Comment by elopatin-uc3** [comment]
Collection documentation:
https://docs.google.com/document/d/1DpTPlntg6iLqP0geSUFTEcW1_4US7xHbX9mPWagwxJ8/edit?usp=sharing

**Comment by elopatin-uc3** [comment]
Planning to create a new ownership object associated with UCLA, in order to facilitate reporting for this first grant-based collection. Need to investigate if we should be using the same SLA object for UCLA; assume yes, and will look for examples.

**Comment by elopatin-uc3** [comment]
There are two SLA objects for UCLA: `ucla_lib_service_level_agreement` and `ucla_womenshealth_service_level_agreement`. Multiple collections reside under the UCLA Library SLA, and as this project is directly associated with the library, we should use this SLA. That said, we will still create a separate Ownership object for the new Pal Museum collection.

**Comment by elopatin-uc3** [comment]
UCLA Palestinian Museum ownership object ARK created:
https://ezid.cdlib.org/id/ark:/13030/j2610974

**Comment by elopatin-uc3** [comment]
PRs out for new stage and production ingest profiles:
Stage: https://github.com/cdlib/mrt-ingest-profile/pull/11
Prod: https://github.com/cdlib/mrt-ingest-profile/pull/12 

@mreyescdl when you have a chance, please review these. thanks!

**Comment by elopatin-uc3** [comment]
LDAP entries created on Stage for the Pal Museum collection. Mark, Terry and Eric have access to it in the UI. Also created a user for Dawn Childress at UCLA.

Tested: elopatin and dchildress login on Stage, and can see the collection (though initial owner and collection objects still need to be submitted).

I will hold off from making the LDAP production entries, as I don't want to risk cutting off access to collections if something's wrong with the collection profile. In the past, I missed adding the submissionProfile information (defined in the profile) and this prohibited access to other collections by my user, and I believe other users. Even though the profiles turned out OK on Stage, I'm just being cautious before the break.

**Comment by mreyescdl** [comment]
Owner and Collection objects submitted for Stage

**Comment by elopatin-uc3** [comment]
Stage collection setup complete.

**Comment by elopatin-uc3** [comment]
New Owner, Collection and Submission profiles created. New ARK for production minted by Coll Admin: ark:/13030/m5909f6n
