### ISSUE TITLE
Campus dashboard design

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#400]
#### Summary
Campus interviews for input pertaining to dashboard design are taking place during the latter half of August, and first half of September. Use cases and observations are being recorded here:
https://docs.google.com/document/d/1kUo2iyUikasE1kS6TWX9AFBoaNTYpZcWY35dt0yX5pw/edit?usp=sharing

Input will be used to help establish which elements of a campus dashboard are most widely agreed upon to be beneficial. 

#### Tasks
- [x] Complete first round of campus interviews. These conversations will continue once nascent dashboards are available to walk through.
- [x] Enumerate dashboard elements that are perceived to be of high value per interviews.
- [x] Experiment with JSON data in Tableau for above elements. 
- [x] Research Tableau JSON API usage: https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_concepts_fundamentals.htm
- [x] Work with @terrywbrady to define Merritt Admin changes needed to support integration with Tableau using JSON output.

**Comment by elopatin-uc3** [comment]
UC Berkeley Library dashboard created.

Next steps: Create other campus dashboards, determine how to host on UCOP Tableau server
