### ISSUE TITLE
NRLF submissions for UCB

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#402]
#### Summary 
New submission (11.2k objects) for UCB

#### Tasks
- [x] Correct collection name typo from NRFL, to NRLF
- [x] Convert original manifest from latin1 to utf-8 encoding
- [x] Correct manifest profile to `mrt-single-file-batch-manifest`
- [x] Divide up original manifest with 11.2k objects into smaller manifests of 2k objects each
- [x] Submit manifests and monitor progress

**Comment by elopatin-uc3** [comment]
Collection name change requires three actions: collection and input profile updates, database update, ldap update.

**Comment by elopatin-uc3** [comment]
First 6K objects submitted and processed. Will submit remainder by 7/22.

**Comment by elopatin-uc3** [comment]
All manifests submitted, but according to the UI object count, we are missing two objects out of 11,201. Going to attempt to identify these.

**Comment by elopatin-uc3** [comment]
One was a duplicate entry in the manifest:
`http://digitalassets.lib.berkeley.edu/nrlftoc/ucb/text/184655691J-B4094226.pdf |  |  |  |  | 184655691J-B4094226.pdf |  | b213590190 |  | Barthes après Barthes : une actualité en questions : actes du colloque international de Pau, 22-24 novembre 1990 / textes réunis par Catherine Coquio et Régis Salado. 184655691J-B4094226.pdf`

Still trying to determine what happened to the other one.
