### ISSUE TITLE
To facilitate manifest creation, provide a .CSV to .checkm web form in the UI

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#420]
#### Summary
Merritt user documentation provides guidance on how to make use of Excel macros in a sample document to create .checkm manifest files from .csv files. Said sample document is from 2010, and due to Excel's use of VB, utf-8 encoding is not supported. This results in loss of special characters, including diacritics, in manifest content (e.g. local IDs) when creating .checkm files from utf-8-encoded .csv's.

We should author an updated tool (web form) that provides a way to submit a .csv, allows a user to specify a manifest profile type, and then returns a .checkm for user-authenticated submission through the UI.

##### For all following use cases:
- A user should be required to select the type of manifest that is being uploaded: Object, Batch of Containers, Batch of Files, Batch of Manifests
- Validation of file contents should occur: The .csv has the correct columns for the desired manifest type, no pipe containers are included in the .csv data, a .csv should be limited to a reasonable line count (e.g. 10K lines, or a number of lines which begins to impact browser performance), data is present in columns that are required. 

##### Use case: Object Manifest
User uploads a CSV that is purposed to become an Object manifest. It has the following columns: fileUrl, hashAlgorithm, hashValue, fileSize, fileLastModified, fileName (only fileURL and fileName are required)
Result: an object manifest .checkm file is presented for download
Sample data: https://raw.githubusercontent.com/CDLUC3/mrt-doc/main/sampleFiles/4blocks.checkm

##### Use case: Batch of Containers Manifest
User uploads a CSV that is purposed to become a Batch of Containers manifest. It has the following columns: 
fileUrl, hashAlgorithm, hashValue, fileSize, fileLastModified, fileName, primaryIdentifier, localIdentifier, creator, title, date
(only fileURL and fileName are required)
Result: a batch of containers manifest .checkm file is presented for download
Sample data: https://raw.githubusercontent.com/CDLUC3/mrt-doc/main/sampleFiles/sampleBatchOfContainers.checkm

##### Use case: Batch of Files Manifest
User uploads a CSV that is purposed to become a Batch of Files manifest. It has the following columns:
fileUrl, hashAlgorithm, hashValue, fileSize, fileLastModified, fileName, primaryIdentifier, localIdentifier, creator, title, date
(only fileURL and fileName are required)
Result: a batch of files manifest .checkm file is presented for download
Sample data: https://raw.githubusercontent.com/CDLUC3/mrt-doc/main/sampleFiles/sampleBatchOfFiles.checkm

##### Use case: Batch of Manifests manifest
User uploads a CSV that is purposed to become a Batch of Manifests manifest. It has the following columns:
fileUrl, hashAlgorithm, hashValue, fileSize, fileLastModified, fileName, primaryIdentifier, localIdentifier, creator, title, date
(only fileURL and fileName are required)
Result: a manifest of manifests .checkm file is presented for download
Sample data: https://raw.githubusercontent.com/CDLUC3/mrt-doc/main/sampleFiles/sampleBatchOfManifests.checkm

All sample data:
https://github.com/CDLUC3/mrt-doc/wiki/Sample-data

#### Tasks
- [ ] Create a web form that provides a means to upload a .csv file which contains content intended for a Merritt manifest. This form should include a required option to select a desired manifest type (batch of files, batch of containers, batch of manifests). 
- [ ] In the web form, include two links to associated manifest documentation: https://github.com/CDLUC3/mrt-doc/wiki/Manifests and https://github.com/CDLUC3/mrt-doc/wiki/Sample-data
- [ ] Once in prototype form, discuss final form aspects: placement, appearance, access 
- [ ] Update associated manifest documentation with information about the new web form, and remove information related to the merrittManifest.xls.

**Comment by terrywbrady** [comment]
@elopatin-uc3 , can this be closed?
