### ISSUE TITLE
New Japanese American News collection for UCB

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#445]
Create new "Japanese American News" collection for owner UCB Library.

#### Tasks
- [x] Create collection documentation
- [x] Create collection profile
- [x] Add collection owner (introduced in collection profile*)
- [x] Mint collection ARK
- [x] Submit collection object
- [x] Create associated entries in LDAP
- [x] Add collection to inventory database
- [x] Update collection record with name, mnemonic, privs 
- [x] Set primary storage node
- [x] Add secondary storage nodes to inv_collections_inv_nodes table (Glacier and Wasabi)
- [x] In EZID, set collection Status (to unavailable) and Harvesting option (to No)

**Comment by elopatin-uc3** [comment]
Collection doc: https://docs.google.com/document/d/1qBpwJRp2Fi7v72XUAlmVwBCEUETdX1HbX2xS04yPPPc/edit?usp=sharing

**Comment by mreyescdl** [comment]
Collection object created in production:
```        
       Job ID: jid-b79ed1c0-4b9d-4527-a0ce-e2d4614e8ef9
        Primary ID: ark:/13030/m52z6j2f
        Version: 1
        Filename: README
        Object title: UC Berkeley Library Japanese American News
        Object state: http://storage.cdlib.org:35121/state/9501/ark%3A%2F13030%2Fm52z6j2f?t=xhtml
        Submission date: 2020-08-31T15:40:34-07:00
        Completion date: 2020-08-31T15:40:37-07:00
        Persistent URL: http://n2t.net/ark:/13030/m52z6j2f
        Status: COMPLETED
```

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl

**Comment by elopatin-uc3** [comment]
@mreyescdl I'm finished with LDAP entries. When I look in the inv database and search for the collection via ARK, the mnemonic is not there yet. Is it OK if I add it manually?

~~~
mysql> select * from inv_collections where ark="ark:/13030/m52z6j2f" \G
*************************** 1. row ***************************
                id: 427
     inv_object_id: 3061161
               ark: ark:/13030/m52z6j2f
              name: NULL
          mnemonic: NULL
    read_privilege: NULL
   write_privilege: NULL
download_privilege: NULL
      storage_tier: NULL
 harvest_privilege: none
1 row in set (0.06 sec)

**Comment by mreyescdl** [comment]
@elopatin-uc3 
I'm not sure how the collection data is populated.  Yes, please add manually if you can.
Ideally, the Inventory service would handle this task.

**Comment by elopatin-uc3** [comment]
Okay, just added it manually. Looking back at my notes, I've had to do this before. I've also updated the inv_collections entry with priv and storage tier information, so I think this collection is complete.
