### ISSUE TITLE
Vintage dissertation submission for UCLA

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#495]
https://help.escholarship.org/a/tickets/79005

#### Tasks
- [x] Construct XML metadata for ETD and package with PDF
- [x] Upload to ETDs server and run `geteds.py`
- [x] Monitor progress through to eScholarship

**Comment by elopatin-uc3** [comment]
XML file created with notes that need to be addressed by UCLA graduate division. I've posted this to the ticket in FreshDesk for feedback. 

I've also created a test ETD zip file and posted it to the SFTP server for processing on Stage. It is picked up by `getetds.py`, but for some reason the script cannot submit it to Merritt. I can do so via curl on the same ETDs stage server host. Will share the error with the team shortly to diagnose.

**Comment by elopatin-uc3** [comment]
This task is finally complete. Testing was done on the ETDs stage host which resulted in the dissertation being ingested into the Stage UCLA ETDs collection. Subsequent ingest into production occurred, and the eSchol harvest published it:
https://escholarship.org/uc/item/2sc0h2q8

That said, there was an unusual delay in the eSchol harvest, which took the better part of 24 hours to complete. There were no errors related to this dissertation.
