### ISSUE TITLE
Create integration test suite credentials for Sword/OAI workflow

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#545]
The `mrt-integ-tests` should be run from our DEV servers in order to verify stage and production.  The test suite should use Merritt credentials that are stored in SSM and accessible to the DEV server.

| Test Case | Stage | Production | Note |
|-----------|-------|------------|------|
|View home page | Done | Done ||
|Login in as guest | Done | Done ||
|Navigate to collection | Done | Done |Which collection?|
|Search for object | Done | Done |Any specific object?|
|View object page | Done | Done |Any specific object?|
|View version page |Done | Done ||
|Presigned file retrieval from S3 | Done | Done |Note collection to use|
|Presigned file retrieval from SDSC | Done | TBD |Note collection to use|
|Presigned file retrieval from Wasabi | Done | No primary node exists | Is it sufficient to test this in stage?|
|Presigned object retrieval | Done | Done |Note collection/object to use|
|Files with special characteristics | Defer* | Defer* |Is this level of testing needed when validating a system patch?|
|Objects with special characteristics | Defer* | Defer* |Is this level of testing needed when validating a system patch?|
|Object submission to demo collection | Done | Done |Use existing test logic to assign a unique local id|
|Verify object submission to demo collection | Done | Done |Search by local id|
|Verify object in atom feed | TBD | TBD ||
|Verify object submission through OAI feed | TBD | TBD |Is OAI supported for the demo collection?|
|Object submission via sword? | TBD | TBD |Is this useful to test separately from Dryad?|
|5G File submission to demo collection | Defer* | Defer* |Use existing test logic to assign a unique local id|
|5G file retrieval demo collection | Defer* | Defer* |Verify object retrieval.  NOTE: perform periodic pruning of demo collection.|

## Defer* Notes
- Create new/separate tickets to test specific functionality

## TODO
- [x] Explicitly identify collections/objects for tests listed above
- [x] Request minimal LDAP credentials for stage and prod to meet the test suite needs
- [x] Add credentials to SSM
- [x] Write test suite for stage and prod
- [x] Document test suite execution
- [x] Train folks on test suite execution
- [ ] Create Stage and Production collections for use with SWORD deposit tests #605

**Comment by elopatin-uc3** [comment]
@elopatin-uc3 to specify collections and user accounts/roles for Stage and Production.

**Comment by elopatin-uc3** [comment]
@terrywbrady I've set up Stage and Production test accounts for automation. 
These have access as follows: 

Stage access:
- Demo Merritt collection (r/w/d) – primary is Minio
- CDL Wasabi test collection (r/w/d) – primary is Wasabi

Production access:
- Demo Merritt collection (r/w/d) – primary is S3
- (no demo collections with Minio or Wasabi as primary are available)

**Comment by terrywbrady** [comment]
@elopatin-uc3 , in order to add the sword --> oai workflow as well, we would need to (1)ingest into a harvestable collection OR (2) make demo harvestable.  We can discuss if this would be useful.

**Comment by elopatin-uc3** [comment]
Making the production demo collection harvestable is fine by me, @terrywbrady. I'm looking into related settings in EZID and the inv db now.

**Comment by elopatin-uc3** [comment]
Per discussion in slack, rather than make our stage and prod demo collections harvestable, we will create new collections to test harvesting.

**Comment by terrywbrady** [comment]
@elopatin-uc3 , I simplified the grid to highlight that the only remaining work for this ticket is the Sword/OAI feed and testing the atom feed.

Should this ticket move back to "In Progress" to show that there is remaining work?

**Comment by elopatin-uc3** [comment]
Thanks @terrywbrady for simplifying the grid. Yes, this should move back to In Progress.

**Comment by elopatin-uc3** [comment]
Ticket filed for creating test collections: #605
