### ISSUE TITLE
Pal Museum file transfer and metadata logistics

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#547]
Logistics surrounding the process of formulating objects, recording metadata, moving files from local drives to EFS and ingesting objects are here: 
https://docs.google.com/document/d/1Ma8DilH8FNTN-QJJaVwjHWZSiEcoXj-D3cNseFiaTNA/edit?usp=sharing

#### Tasks
- [x] Confirm timing for use of Snowcone devices, as we can only have these for 5 days
- [ ] Generate checksums for all files on Pal Museum drives using Terry's File Analyzer application
- [x] Copy files to Snowcone drive 1
- [x] Copy file to Snowcone drive 2
- [x] Return Snowcones
- [ ] Generate checksums for files on EFS
- [ ] Obtain MODS files from UCLA: 72K files (on Box)

**Comment by elopatin-uc3** [comment]
CDLSYS ticket 13814 is tracking our request to use two AWS Snowcone devices for data transfer.

**Comment by elopatin-uc3** [comment]
With Martin's assistance, and several trials and tribulations, all files from the Museum's Seagate drives have been copied onto two Snowcones. I am planning to return them tomorrow.

**Comment by elopatin-uc3** [comment]
Copying down MODS files from UCLA now.
