### ISSUE TITLE
Add production collection that uses Wasabi as primary storage node

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#548]
#### Summary
In order to have a way of testing the use of Wasabi as a primary node, we need to create a collection in production. We already have a corresponding collection on stage.

#### Tasks
- [ ] Create collection documentation
- [ ] Mint collection ARK
- [ ] Mint owner ARK
- [ ] Create collection profiles
- [ ] Set primary storage node
- [ ] Add collection owner object (introduced in collection profile*)
- [ ] Submit collection object
- [ ] Create associated entries in LDAP
- [ ] Add collection to inventory database
- [ ] Update collection record with name, mnemonic, privs 
- [ ] Add secondary storage nodes to inv_collections_inv_nodes table (Glacier and Wasabi)
- [ ] In EZID, set collection Status (to unavailable) and Harvesting option (to No)
