### ISSUE TITLE
New UC Santa Cruz Library Cabrillo Music Festival Collection

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#565]
#### Summary
Request from Sue Perry to create a new collection:
Collection Name: UCSC Library Cabrillo Music Festival Collection
user(s): Sue Perry ('chesley' user in LDAP)
permissions: r/w/d

#### Tasks, Production
- [x] Create collection documentation
- [x] Mint collection ARK
- [x] Create collection profiles
- [x] Add collection owner object (introduced in collection profile*)
- [x] Submit collection object
- [x] Create associated entries in LDAP
- [x] Add collection to inventory database
- [x] Update collection record with name, mnemonic, privs
- [x] Set primary storage node (introduced in collection profile)
- [x] Add secondary storage nodes to inv_collections_inv_nodes table (Glacier and Wasabi)
- [x] In EZID, set collection Status (to unavailable) and Harvesting option (to No)

**Comment by elopatin-uc3** [comment]
Collection documentation:
https://docs.google.com/document/d/1kHEgGyt-W-ALdqnayQhTH-O1eeyOCcezhMVIeATyhhg/edit?usp=sharing

**Comment by elopatin-uc3** [comment]
Noting PR for profiles: https://github.com/cdlib/mrt-ingest-profile/pull/13

**Comment by mreyescdl** [comment]
Collection object created

**Comment by elopatin-uc3** [comment]
Collection setup complete.
