### ISSUE TITLE
Establish Stage and Production collections to test harvesting via automation

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#569]
#### Summary
One of the desired cases in the new Merritt automated integration test suite covers testing OAI feed harvesting. See #545 for more information. This ticket tracks creating stage and production collections that will have public harvest privileges and a limited number of objects for use with this test case.

#### Tasks: Stage
- [ ] Create collection documentation
- [ ] Mint collection ARK
- [ ] Mint owner ARK
- [ ] Create collection profiles
- [ ] Add collection owner object (introduced in collection profile*)
- [ ] Submit collection object
- [ ] Create associated entries in LDAP
- [ ] Add collection to inventory database
- [ ] Update collection record with name, mnemonic, privs 
- [ ] Set primary storage node (introduced in collection profile)
- [ ] Add secondary storage nodes to inv_collections_inv_nodes table
- [ ] In EZID, set collection Status (to unavailable) and Harvesting option (to No)

#### Tasks: Production
- [ ] Create collection documentation
- [ ] Mint collection ARK
- [ ] Mint owner ARK
- [ ] Create collection profiles
- [ ] Add collection owner object (introduced in collection profile*)
- [ ] Submit collection object
- [ ] Create associated entries in LDAP
- [ ] Add collection to inventory database
- [ ] Update collection record with name, mnemonic, privs 
- [ ] Set primary storage node (introduced in collection profile)
- [ ] Add secondary storage nodes to inv_collections_inv_nodes table (Glacier and Wasabi)
- [ ] In EZID, set collection Status (to unavailable) and Harvesting option (to No)

**Comment by terrywbrady** [comment]
merritt_sword_test created in stage and prod
