### ISSUE TITLE
New UCB Collection: UC Berkeley Library Election Ephemera Collection

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#581]
#### Summary
New collection requested by David Triebwasser:
UC Berkeley Library Election Ephemera Collection
user: ucblap, davidtriebwasser
permissions: r/w/download

#### Tasks, Production
- [x] Create collection documentation
- [x] Mint collection ARK
- [x] Create collection profiles
- [x] Add collection owner object (introduced in collection profile*)
- [x] Submit collection object
- [x] Create associated entries in LDAP
- [x] Add collection to inventory database
- [x] Update collection record with name, mnemonic, privs
- [x] Set primary storage node (introduced in collection profile)
- [x] Add secondary storage nodes to inv_collections_inv_nodes table (Glacier and Wasabi)
- [x] In EZID, set collection Status (to unavailable) and Harvesting option (to No)

**Comment by elopatin-uc3** [comment]
Collection intake form created:
https://docs.google.com/document/d/15qBQaA_4fvgm9LohjTVvSr-tufeY1tN3c37Ms7Rmw_Y/edit?usp=sharing

**Comment by elopatin-uc3** [comment]
https://ezid.cdlib.org/id/ark:/13030/m5p89wdw

**Comment by elopatin-uc3** [comment]
https://github.com/cdlib/mrt-ingest-profile/pull/15
