### ISSUE TITLE
New UCB Collection: UC Berkeley Library IGS Digital Collection

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#601]
#### Summary
New collection requested by David Triebwasser:
UC Berkeley Library IGS Digital Collection
user: ucblap, davidtriebwasser
permissions: r/w/download

#### Tasks, Production
- [x] Create collection documentation
- [x] Mint collection ARK
- [x] Create collection profiles
- [x] Submit collection admin object
- [x] Create associated entries in LDAP
- [x] Add collection to inventory database (introduced via collection profile)
- [x] Update collection record with name, mnemonic, privs
- [x] Set primary storage node (introduced in collection profile and added to Inv when admin object is submitted)
- [x] Add secondary storage nodes to inv_collections_inv_nodes table (Glacier and Wasabi)
- [x] In EZID, set collection Status (to unavailable) and Harvesting option (to No)

**Comment by elopatin-uc3** [comment]
Collection intake form created:
https://docs.google.com/document/d/1W_qAUVQq5HDD6oXCWt6kipK8GccCAsKwWqj7PYLWxBo/edit?usp=sharing

**Comment by elopatin-uc3** [comment]
Collection ARK: ark:/13030/m5bw33v1
https://ezid.cdlib.org/id/ark:/13030/m5bw33v1

**Comment by elopatin-uc3** [comment]
Collection profiles PR: https://github.com/cdlib/mrt-ingest-profile/pull/16
