### ISSUE TITLE
New UCSF collections for SFPL and GLBT Historical Society PRODUCTION

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#603]
#### Summary
UCSF has requested new collections to house Nuxeo content for the San Francisco Public Library and the GLBT Historical Society.  This ticket tracks work for Production.

#### Tasks, Production
- [ ] Create collection documentation
- [ ] Mint collection ARK
- [ ] Create collection profiles
- [ ] Add collection owner object (introduced in collection profile*)
- [ ] Submit collection object
- [ ] Create associated entries in LDAP
- [ ] Add collection to inventory database
- [ ] Update collection record with name, mnemonic, privs
- [ ] Set primary storage node (introduced in collection profile)
- [ ] Add secondary storage nodes to inv_collections_inv_nodes table (Glacier and Wasabi)
- [ ] In EZID, set collection Status (to unavailable) and Harvesting option (to No)
