### ISSUE TITLE
UCB: Julian P. Graham Collection of Photographic Negatives

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#626]
Collection Repo: UC Berkeley Library Julian P. Graham Collection of Photographic Negatives
user: ucblap, davidtriebwasser
permissions: r/w/download

#### Tasks: Production
- [x] Create collection intake form
- [x] Mint collection ARK
- [ ] Create collection profiles
- [ ] Submit collection admin object
- [ ] Create associated entries in LDAP
- [ ] Add collection to inventory database (introduced via collection profile)
- [ ] Update collection record with name, mnemonic, privs
- [ ] Set primary storage node (introduced in collection profile and added to Inv when admin object is submitted)
- [ ] Add secondary storage nodes to inv_collections_inv_nodes table (Glacier and Wasabi)
- [x] In EZID, set collection Status (to unavailable) and Harvesting option (to No)

**Comment by elopatin-uc3** [comment]
Collection intake form created:
https://docs.google.com/document/d/1JnaXMkzfBmnA4nlLL3E19Pl0MA-Dblj_sufg2M86zb0/edit?usp=sharing

**Comment by elopatin-uc3** [comment]
Mark discovered this collection already exists:
https://ezid.cdlib.org/id/ark:/13030/m518681g

Waiting for confirmation from David T. about loading new content into the existing collection.

**Comment by elopatin-uc3** [comment]
Mark discovered UCB already has a Graham negatives collection. After some deduplication on his side, David T. asked us to submit to the existing collection. Closing this ticket.
