### ISSUE TITLE
New UCLA Frontera collection deposits

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#631]
#### Summary
UCLA would like to review current content in Frontera and deposit new content that's not yet in Merritt.

#### Tasks
- [x] Meet with UCLA archivist, Geno Sanchez to discuss object composition and metadata (scheduled for 3/25).
- [x] Generate list of files in the collection via inv db dump
- [x] Set up Merritt account for GS
- [x] Gap analysis using new File Analyzer routine added by Terry
- [x] Additional gap analysis with new, full collection spreadsheet provided by the Arhoolie foundation
- [x] Isolate 578 records in Merritt that don't have wav files and see if these overlap with the 942 that do not match the latest foundation spreadsheet

Additional tasks TBD

**Comment by elopatin-uc3** [comment]
See also https://github.com/CDLUC3/mrt-doc/issues/632

**Comment by elopatin-uc3** [comment]
used the new routines in the File Analyzer to perform an initial gap analysis. Approximately 3K objects in Merritt were not matched to the source spreadsheet provided by the Arhoolie Foundation. Geno suspects that the foundation's spreadsheet is actually missing entries and will be requesting a new one. Once we have this, another gap analysis will be performed.

**Comment by elopatin-uc3** [comment]
Isolated 578 records without .wav files. Interesting, these all begin with the "F1D1" string that is normally a naming convention reserved for .wav files. All TIFF files whose names begin with "F1D1" correspond to objects w/out TIFFs. Furthermore, the second portion of each TIFF file name is a portion of the ARK string. This leads me to believe that no standard file names were generated for these prior to ingest, and/or they weren't listed on a metadata resource spreadsheet similar to the one we have now from the foundation.

**Comment by elopatin-uc3** [comment]
Update from meeting on May 6, 2021: Geno and Lisa have spoken about an approach to avoid the gap analysis that we haven't been able to narrow down further than the 942 record difference between the Merritt object list, and entries on the foundation spreadsheet with unique .wav files listed. Rather than attempt to match these records using other song metadata, which appears like it would be very difficult, they would instead like to ingest all new content based on the latest foundation spreadsheet, and then remove the original objects from the Merritt collection.

**Comment by elopatin-uc3** [comment]
Given the above approach has been at least tentatively decided upon, I'm going to move this ticket to Deployed/Done. Note that all work has been backed up to Box in Merritt Campus Projects/UCLA/Frontera/From Eric
