### ISSUE TITLE
Create UC Berkeley Library Early Readers collection

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#634]
Collection Repo: UC Berkeley Library Early Readers
user: ucblap, davidtriebwasser
permissions: r/w/download

#### Tasks: Production
- [x] Create collection intake form
- [x] Mint collection ARK
- [x] Create collection profiles
- [x] Submit collection admin object
- [x] Create associated entries in LDAP
- [x] Add collection to inventory database (introduced via collection profile)
- [x] Update collection record with name, mnemonic, privs
- [x] Set primary storage node (introduced in collection profile and added to Inv when admin object is submitted)
- [x] Add secondary storage nodes to inv_collections_inv_nodes table (Glacier and Wasabi)
- [x] In EZID, set collection Status (to unavailable) and Harvesting option (to No)

**Comment by elopatin-uc3** [comment]
Collection intake form created. Collection ARK minted:
https://docs.google.com/document/d/1kF2ZzEkebq-O6BbN_2evlpxA8N3dyUMU8GjCDVnqCx4/edit?usp=sharing

**Comment by mreyescdl** [comment]
Collection object created

**Comment by elopatin-uc3** [comment]
Noting profiles PR (now merged): https://github.com/cdlib/mrt-ingest-profile/pull/17

**Comment by elopatin-uc3** [comment]
LDAP entries created.
