### ISSUE TITLE
Obtain backup object copies for Southern California Library

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#654]
#### Summary
The Southern California Library has requested that we download copies of the objects in their LSTA collection, and subsequently deliver them to the library.

Collection: 
https://merritt.cdlib.org/m/lsta_socallib

There are 200 objects with 378 versions, taking a total of 3GB. I will use an existing object download script to obtain them and upload them to a Google Drive folder selected by PAD for the transfer.

#### Tasks
- [x] Obtain ARK list for collection
- [x] Run download script on dev box
- [x] Transfer content to local and upload to Google Drive

**Comment by elopatin-uc3** [comment]
Everything uploaded to Google drive folder. Waiting for feedback from Adrian and Christine.

Noting associated FreshDesk ticket: https://help.oac.cdlib.org/a/tickets/87686
