### ISSUE TITLE
Create UC Berkeley Library FSM Cafe Program collection

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#662]
Collection Repo: UC Berkeley Library FSM Cafe Program
user: ucblap, davidtriebwasser
permissions: r/w/download

#### Tasks: Production
- [x] Create collection intake form
- [x] Mint collection ARK
- [x] Create collection profiles
- [x] Submit collection admin object
- [x] Create associated entries in LDAP
- [x] Add collection to inventory database (introduced via collection profile)
- [x] Update collection record with name, mnemonic, privs
- [x] Set primary storage node (introduced in collection profile and added to Inv when admin object is submitted)
- [x] Add secondary storage nodes to inv_collections_inv_nodes table (Glacier and Wasabi)
- [x] In EZID, set collection Status (to unavailable) and Harvesting option (to No)

**Comment by elopatin-uc3** [comment]
Collection intake form:
https://docs.google.com/document/d/1b9nUO61wwMoneAIKdgxrDu2jMlxu9h6j7VWPRdThOJo/edit?usp=sharing

**Comment by elopatin-uc3** [comment]
Profiles PR: https://github.com/cdlib/mrt-ingest-profile/pull/19
