### ISSUE TITLE
Convert createmarc.py to Python 3

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#664]
#### Summary
The ETDs service `createmarc.py` script has been throwing an encoding error for some time now while attempting to process ProQuest .unx. files. This has been investigated via #585 and is thought to be caused by non-ascii characters in the said files. The script has also exhibited an error where ISBN numbers cannot be found for known-published (by ProQuest) ETDs. An ETD published by ProQuest will always have an ISBN number associated with it. 

This latter error has prevented further investigation for #585 and is itself recorded in issue #483. Part of the work done to diagnose the encoding problem has shown that fewer records expose the bug when the key file open operation takes place via a Python 3 interpreter. To this end, the team sees value in converting `createmarc.py` to Python 3. By doing so, the goal is to resolve, or at least partly address both of the above problems. 

Note that if it is not possible to make significant progress on the encoding issue (e.g. being able to process the majority of records in the .unx files with non-ascii characters), then we can also ask ProQuest to deliver .mrc files to us. If this option is desired, then the scope of this ticket will change to encompass handling .mrc files.

Testing can occur on the ETDs service stage instance:
`uc3-etdx2-stg`

Several .unx files are available for use on Stage.
Github repo: https://github.com/CDLUC3/uc3-etds

#### Tasks
- [ ] Convert createmarc.py to Python 3.x: /uc3-etds/tree/master/scripts/createmarc.py
- [ ] Install on stage with a Python virtual environment. See wrapper script: /uc3-etds/blob/master/scripts/createmarc
- [ ] Test with sample .unx files
- [ ] If appropriate, investigate the modification of `createmarc.py` to enable processing of ProQuest .mrc files instead

**Comment by elopatin-uc3** [comment]
Have decide not to move to Python 3.
