### ISSUE TITLE
New UCSF collection & Nuxeo feed: MSS 96-33 Bobbi Campbell Diary

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#671]
Collection Name	
MSS 96-33 Bobbi Campbell Diary	

Collection Description
Selected material from the diary of Bobbi Campbell, nurse and self-identified "AIDS Poster Boy."

Campus Users
"Charles Macquarie, charles.macquarie@ucsf.edu, W/R/D
Polina Ilieva, polina.ilieva@ucsf.edu, W/R/D"

Shared Accounts
UCSF Archives & Special Collections shared account, libraryarchives@ucsf.edu, W/D

#### Tasks, General
- [x] Create Stage collection
- [x] Relay needed ATOM feed info from Adrian to Mark
- [x] Create Nuxeo stage feed
- [x] Create Production collection
- [x] Create Nuxeo production feed
- [x] New user account for libraryarchives@

#### Tasks: Stage
- [x] Create collection intake form
- [x] Mint collection ARK
- [x] Create collection profiles
- [x] Submit collection admin object
- [x] Create associated entries in LDAP
- [x] Add collection to inventory database (introduced via admin object submission after collection profile is live)
- [x] Update collection record with name, mnemonic, privs
- [x] Set primary storage node (introduced via admin object submission after collection profile is live)
- [x] In EZID, set collection Status (to unavailable) and Harvesting option (to No)
- [x] Create and Test Nuxeo script
- [x] Cron Nuxeo script (weekly on Tuesday)

#### Tasks: Production
- [x] Create collection intake form
- [x] Mint collection ARK
- [x] Create collection profiles
- [x] Submit collection admin object
- [x] Create associated entries in LDAP
- [x] Add collection to inventory database (introduced via admin object submission after collection profile is live)
- [x] Update collection record with name, mnemonic, privs
- [x] Set primary storage node (introduced via admin object submission after collection profile is live)
- [x] Add secondary storage nodes to inv_collections_inv_nodes table (Glacier and Wasabi)
- [x] In EZID, set collection Status (to unavailable) and Harvesting option (to No)
- [x] Create and Test Nuxeo script
- [x] Cron Nuxeo script (weekly on Thursday)

**Comment by elopatin-uc3** [comment]
Documentation created:
https://docs.google.com/document/d/1ejYLpYcZlhABXJCm4aFNNtWHu8b6j5UCztiiXAjlzcI/edit?usp=sharing

ARK: 
ark:/13030/m5nw59j1

EZID:
https://ezid.cdlib.org/id/ark:/13030/m5nw59j1

FD:
https://help.oac.cdlib.org/a/tickets/88252

**Comment by elopatin-uc3** [comment]
Need to contact Charlie about setting up an LDAP entry for the libraryarchives address.

**Comment by elopatin-uc3** [comment]
Created LDAP account for ucsf_lib_archives in prod and stage. ARK: ark:/99166/p98k7534j
Created LDAP accounts for CM and PI on stage.

**Comment by mreyescdl** [comment]
Stage and Production objects created.  
Both have the same primary ID.

**Comment by aturner** [comment]
The endpoint will be https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_3684.atom

**Comment by elopatin-uc3** [comment]
Also note, Per Barbara, the ATOM feeds are on S3 in this format:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_[Collection Registry ID].atom

**Comment by elopatin-uc3** [comment]
@mreyescdl Adrian Turner just confirmed that the above ATOM feed is now available.

**Comment by elopatin-uc3** [comment]
Sent a note to Charlie and Adrian to review results of the first harvest on stage:
https://merritt-stage.cdlib.org/m/ucsf_lib_bobbicampbell

**Comment by elopatin-uc3** [comment]
@mreyescdl UCSF has approved of the Bobbi Campbell Diary collection content in stage. Please set up the same harvest in production when time allows. Thanks!

**Comment by mreyescdl** [comment]
Production Nuxeo setup is complete.
Manually ran harvesting prior to Thursday's run

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl
