### ISSUE TITLE
New UCSF collection & Nuxeo feed: MSS 98-47 ACT-UP Golden Gate records

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#672]
https://help.oac.cdlib.org/a/tickets/88252

Collection Name	
MSS 98-47 ACT-UP Golden Gate records

Collection Description
Digitized records of ACT-UP Golden Gate (The AIDS Coalition to Unleash Power)

Campus Users
"Charles Macquarie, charles.macquarie@ucsf.edu, W/R/D
Polina Ilieva, polina.ilieva@ucsf.edu, W/R/D"

Shared Accounts
UCSF Archives & Special Collections shared account, libraryarchives@ucsf.edu, W/D

#### Tasks, General
- [x] Create Stage collection
- [x] Acquire ATOM feed info for Mark
- [x] Set up Nuxeo stage process and cron
- [x] Create Production collection
- [x] Set up Nuxeo production process and cron

#### Tasks: Stage
- [x] Create collection intake form
- [x] Mint collection ARK
- [x] Create collection profiles
- [x] Submit collection admin object
- [x] Create associated entries in LDAP
- [x] Add collection to inventory database (introduced via admin object submission after collection profile is live)
- [x] Update collection record with name, mnemonic, privs
- [x] Set primary storage node (introduced via admin object submission after collection profile is live)
- [x] In EZID, set collection Status (to unavailable) and Harvesting option (to No)
- [x] Create and Test Nuxeo script

#### Tasks: Production
- [x] Create collection intake form
- [x] Mint collection ARK
- [x] Create collection profiles
- [x] Submit collection admin object
- [x] Create associated entries in LDAP
- [x] Add collection to inventory database (introduced via admin object submission after collection profile is live)
- [x] Update collection record with name, mnemonic, privs
- [x] Set primary storage node (introduced via admin object submission after collection profile is live)
- [x] Add secondary storage nodes to inv_collections_inv_nodes table (Glacier and Wasabi)
- [x] In EZID, set collection Status (to unavailable) and Harvesting option (to No)
- [x] Create and Test Nuxeo script
- [x] Cron Nuxeo script (weekly on Thursday)

**Comment by elopatin-uc3** [comment]
Collection documentation created: 
https://docs.google.com/document/d/1m3JcqaNa1xbH5nB2lmSN1FEbxm5tkP4YOnzFBlnFWA4/edit?usp=sharing

ARK: ark:/13030/m5c88h8c

**Comment by elopatin-uc3** [comment]
Registry entry now available for this collection:
https://registry.cdlib.org/308/act-up-golden-gate-records-1988-1993/

@mreyescdl 
The associated feed should available on Tuesday 7/20:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_308.atom

**Comment by elopatin-uc3** [comment]
PRs for profiles:
Stage: https://github.com/cdlib/mrt-ingest-profile/pull/24
Prod: https://github.com/cdlib/mrt-ingest-profile/pull/25

**Comment by mreyescdl** [comment]
Stage Collection admin object submitted
Nuxeo script created and run manually, creating 20 objects:

https://merritt-stage.cdlib.org/m/ucsf_lib_actup

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl

**Comment by mreyescdl** [comment]
Production collection admin object submitted

Nuxeo script created and run manually, creating 20 objects
Scheduled weekly cron wun on UI03 at 7:30 AM

https://merritt.cdlib.org/m/ucsf_lib_actup

**Comment by mreyescdl** [comment]
Did not schedule weekly Stage cron.  Will do, if process changes or if Eric feels it is necessary.

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl ! No need to schedule the weekly Stage cron. I'll remove that task from the list.

**Comment by elopatin-uc3** [comment]
Moving this to Done/Deployed.

**Comment by mreyescdl** [comment]
Stage submission is complete, 1674 objects in total

Please have user review: https://merritt-stage.cdlib.org/m/ucm_lib_ucce_sbslo
