### ISSUE TITLE
Generate XML for vintage UCSD thesis: Boord, D.

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#676]
Publish vintage thesis in eScholarship.

Request from:
Laura Schwartz
Arts & Humanities Collection Strategist
Visual Arts Librarian
UC San Diego

Thesis: Boord, Daniel – originally published 1980
No record in ProQuest
Title: _Poetics on Five Dollars a Day_

##### Tasks
- [x] Create XML based on thesis PDF – ensure use of unique Local ID in umi URL!
- [x] Request XML review from Laura S. and author
- [x] Ingest into Merritt via ETDs service
- [x] Confirm publication

**Comment by elopatin-uc3** [comment]
XML is being sent to author for review.

UCSD contact Laura S. has asked that we look into a possible workflow for updating ProQuest with vintage ETD information. This update would be completed by campus staff.
