### ISSUE TITLE
[Minio/<PROVIDER> checklist] Add Storage node to <ENV> inventory database

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#68]
The storage node is not fully functional till added to the inventory database. Traditionally, this is done by manually adding a dummy object to Storage and processing it through the Inventory service.

**TO DO:** something simpler

 - [ ] Create dummy object & corresponding storage manifest in Storage
 - [ ] Add URL for storage manifest to ZK queue for processing by Inventory service
 - [ ] After processing by Inventory service, check inv_nodes table to make sure record was created
 - [ ] Delete dummy object from Inventory database
 - [ ] Delete dummy object from Storage
