### ISSUE TITLE
Deploy Merritt Cron Server

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#687]
## Assumptions
- [ ] Need prd/stg boxes
- [ ] Need aws lambda invoke permissions
- [ ] Need Ruby
- [ ] Need Mysql client
- [ ] Instance type thoughts? (depends on crons to migrate)
- [ ] Need SSM access (by nature of being in stg/prd)

## Todo
- [ ] Move lambda arn SSM entries from /dev/ to a generic key
- [ ] Create a new code repo `cdluc3/mrt-crons` for code that is invoked by cron
  - @ashleygould , does is seem OK to make this repo merritt specific?  Other services could have a separate repo if they have cron scripts to manage 
  - Puppet will manage the actual cron entries.  
  - Code will be refreshed with a git pull
  - A refresh script will perform tasks like bundle install as needed

## Crons to include
- [ ] Consistency reports. (move from https://github.com/CDLUC3/mrt-admin-lambda/tree/main/consistency-driver)
- [ ] Billing cron 
  - `${HOME}/bin/uc3-mysql.sh billing -- -e 'call update_billing_range();'`
  - `${HOME}/bin/uc3-mysql.sh billing -- -e 'call update_object_size();'`
- [ ] Nuxeo feeds - (selectively move from https://github.com/CDLUC3/mrt-dashboard/tree/main/lib)
  - This could necessitate an instance type comparable to the UI boxes  
- [ ] Zookeeper reports (if possible)

## Crons to stop running
- legacy billing script
- db-perf.pl
  - @mreyescdl , that code should be deleted as well to remove any old credentials

**Comment by mreyescdl** [comment]
`
Puppet Controlled Crons
-----------------------
Host level
        uc3-mrtinv01x2-stg
                /dpr2/bin/dbSyncCron.sh
        uc3-mrtui03x2-prd
                Nuxeo prod - Needs UI env
        uc3-mrtreplic01x2-prd
                Clean up temp files and dirs
        uc3-mrtreplic02x2-prd
                Clean up temp files and dirs
        uc3-mrtui01x2-stg
                Nuxeo stage - Needs UI env
        uc3-mrtinv01x2-prd
                /dpr2/bin/dbtest/db-perf.pl
                /dpr2/bin/merritt_billing/run_mrt_dbquery.bash
                /dpr2/bin/dbSyncCron.sh
Sub-Service level
        uc3-mrt-store
                cleanup_storage_containers
                cleanup_storage_temp
                cleanup_tomcat_logs
        uc3-mrt-access
                cleanup_storage_containers
                cleanup_storage_temp

Manual Crons
------------
uc3-ldap-stg.cdlib.org (ELB)
        uc3-ldap01x2-stg
                export_ldap
                uc3ldap-rotate_and_compress_logs
uc3-ldap.cdlib.org (ELB)
        uc3-ldap01x2-prd
                check_replication status
                export_ldap
                uc3ldap-rotate_and_compress_logs
        uc3-ldap02x2-prd
                check_replication status
                export_ldap
                uc3ldap-rotate_and_compress_logs
`

**Comment by terrywbrady** [comment]
Repository created: 
- https://github.com/CDLUC3/mrt-cron
- Pivotal: https://www.pivotaltracker.com/n/projects/2157590/stories/178438686

**Comment by mreyescdl** [comment]
Superseded by https://github.com/CDLUC3/mrt-doc/issues/753

Please close this ticket @elopatin-uc3
