### ISSUE TITLE
Remove Dryad content copy from Wasabi

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#692]
In a recent discussion with Finance regarding storage expansion, it was noted that the correct configuration for the Dryad collection should have been referenced from this document:
https://docs.google.com/document/d/1D5sWnubPOfsRR_OsxVF6EDf8Z9BsTmAKJy35nk4NOBk/edit

In the "Dryad Preservation Storage" document, the following is specified:
Config | Retrieval Copy 1 | Copy 1Cost $ | Replicated Copy 2 | Copy 2 Cost $ | Additional Copy 3 | Copy 3 | Total Cost to CDL $ | Total Cost to Dryad
-- | -- | -- | -- | -- | -- | -- | -- | --
Old Dash | AWS S3 West | $260/TB/year | SDSC Openstack | $390/TB/year | X | X | $650/TB/year | $0
Old Dryad | AWS S3US East | $270/TB/year | AWS S3US West | $270/TB/year | DANS | $480/TB/year | $0 | $1021/TB/year
New Dryad Long term | AWS S3US East | $270/TB/year | SDSC Minio+ Qumulo | $70/TB/year | Zenodo | $0 | $0 | $340/TB/year

The "Additional Copy 3" for the "New Dryad Long term" storage is Zenodo, not Wasabi.

Whereas we can recharge Dryad for the storage at SDSC, we cannot do so for Wasabi. That said, the copy of Dryad content in Wasabi should be removed.

#### Tasks
- [ ] Stop replication of Dryad collection (cdl_dryad) content to Wasabi
- [ ] Remove Dryad collection content from Wasabi

**Comment by marisastrong** [comment]
- [ ] no longer replicate content to Wasabi for Dryad content
- [ ] remove content from Wasabi

**Comment by elopatin-uc3** [comment]
@dloy We've confirmed with Dryad that they are going to prioritize getting all earlier dataset objects uploaded to Zenodo as a third copy. Daniella will also be checking with Scott to determine what the best way is for us to track the third copy via a persistent identifier.
