### ISSUE TITLE
[Minio/<PROVIDER> checklist] Set up monitors for <ENV>

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#70]
We need to monitor:
1. that Minio is up and accessible from each service host
2. that the Storage service can read from / write to Minio

For (1), we can use the same “smoke test” we used for the initial setup:

```
AWS_ACCESS_KEY_ID=<access key> AWS_SECRET_ACCESS_KEY=<secret key> \
  aws --endpoint-url <URL> s3 ls
```

This should output the bucket name. (**Note:** We don't want to hard-code these keys in the crontab; we should figure out how we're going to manage them in general, but presumably they'll be in the role account environment, or they'll be accessible from a script that can make the actual check, or something like that.)

For (2), we can use the Storage state command (cf. #161990652):

```
curl -X GET 'http://<STORAGE HOST>:35121/state/<NODE#>?t=xml'
```

should return XML including

```
<nod:ok>true</nod:ok>
```

**TO DO:** Update this if/as/when we add a more robust node-specific state command to Audit & Replic; maybe skip the smoke tests in that case and just use those
 - [ ] Set up “smoke test” monitor on each Storage server
 - [ ] Set up “smoke test” monitor on each Replic server
 - [ ] Set up “smoke test” monitor on each Audit server
 - [ ] Set up state check monitor on each Storage server
