### ISSUE TITLE
Merritt API Planning

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#721]
## Brainstorming
- https://confluence.ucop.edu/pages/viewpage.action?pageId=255689700

## TODO
- [ ] Prototype API GW api key
- [ ] Prototype API GW authentication (collection) using Cognito
- [ ] Document endpoints in swagger
- [ ] Review endpoints with prospective clients
- [ ] Prototype swagger --> APIGW synch
- [ ] Prototype APIGW --> Lambda invocation

**Comment by elopatin-uc3** [comment]
@terrywbrady David Triebwasser and David Zuckerman were in touch yesterday with a question about verifying existing records in their collections. They current parse collection ATOM feeds to do so, but are expressing interest in an endpoint that can help them with this effort. Let's take some time at our next Tuesday meeting to discuss.
