### ISSUE TITLE
Establish UC Davis ETDs workflow with ProQuest 

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#759]
#### Summary
Michael Ladisch at UCD has confirmed that all necessary policy changes are in place to publish UC Davis ETDs to eScholarship. The first step will be test ProQuest zip deposits on stage. This requires opening a support ticket with them and contacting appropriate technical staff. We will also need to ensure access to SFTP under the 'proquest' account. I will then work with eSchol to test harvests.

#### Tasks
- [x] Contact PQ and establish case
- [x] Request test deposits on Stage sftp
- [x] ETD service code changes to enable processing
- [x] Establish Collection in Production (#763)
- [x] Coordinate with eSchol for harvest testing

**Comment by elopatin-uc3** [comment]
ProQuest dev team has successfully tested connectivity to sftp and sftp-stg hosts using their public key. Waiting on info for when they will be able to deliver test zips.

**Comment by elopatin-uc3** [comment]
Changes made on Stage: https://github.com/CDLUC3/uc3-etds/pull/8
Two ETD zip files delivered by Proquest to stage sftp today.
Running the getetds script resulted in successful processing of the two zips according to the log. Two queued and completed emails were received. However, it appears these were ingested into the wrong collection? They are not showing up in the stage UC Davis ETDs collection.

**Comment by elopatin-uc3** [comment]
Mark investigated and saw that Inventory failed to process the two submitted objects. He reprocessed them and they completed fine. Snippet from the mysql error:
```
exception:com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
``` 
We'll ask David for more information next.

**Comment by elopatin-uc3** [comment]
A second test with a single zip (modified ucsd > ucd test) ingested without issue. David reported that the two prior objects locked each other out of the inv_c.._inv_objects table. He was surprised the entire table was locked, and is going to write up an issue. That said, this seems to be a rare occurrence.

**Comment by elopatin-uc3** [comment]
PR for production changes:
https://github.com/CDLUC3/uc3-etds/pull/9

**Comment by elopatin-uc3** [comment]
Third and fourth test with a single zip file went fine, though for third I accidentally added the test xml and pdf to an existing zip instead of a new one. The resulting object, that was updated with the fourth test, has four files in it as expected. The db locking issue (expected to be transient) we saw when submitting two zips in the first test has been documented here by David: #783

**Comment by elopatin-uc3** [comment]
I've updated ProQuest and will plan to deploy to production by mid-next week.
