### ISSUE TITLE
New UC Berkeley Library Film-Kurier Collection in production

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#764]
Collection Repo: UC Berkeley Library Film-Kurier Collection
user: ucblap, ucbroa, davidtriebwasser
permissions: r/w/download

#### Tasks: Production
- [ ] Create collection intake form
- [ ] Mint collection ARK
- [ ] Create collection profiles
- [ ] Submit collection admin object
- [ ] Create associated entries in LDAP
- [ ] Add collection to inventory database (introduced via admin object submission after collection profile is live)
- [ ] Update collection record with name, mnemonic, privs
- [ ] Set primary storage node (introduced via admin object submission after collection profile is live)
- [ ] Add secondary storage nodes to inv_collections_inv_nodes table (Glacier and Wasabi)
- [ ] In EZID, set collection Status (to unavailable) and Harvesting option (to No)

**Comment by elopatin-uc3** [comment]
Intake form created:
https://docs.google.com/document/d/1dtYUVQqushaPMj-G7RH1DBiJqSBZp-eaBilv6D2SP94/edit?usp=sharing

LDAP entries done. Collection shows in production UI. Waiting to merge profiles and submit admin object.

**Comment by mreyescdl** [comment]
Collection object created.

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl !
