### ISSUE TITLE
Admin Object Submission Process Feedback

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#779]
## 8/27 - Terry, Eric, and Mark met
- [x] evaluate use of "db only" text in reports
- [ ] add sentence at the top of each report explaining the purpose
- [x] evaluate performance issues loading collAdmin page
  - non issue in prod/stage 
- [ ] add admin object submission instructions
  - [ ] consider creating a video overview as well (for future users) 

## TODO
- [ ] Eric, Mark and Terry should meet to review objects on stage and prod
  - What profile cleanup might be useful
  - What report adjustments might be useful
  - Are any updates needed to the inv_objects.erc_what columns for the admin objects?

**Comment by terrywbrady** [comment]
@elopatin-uc3 , should be closed I think

**Comment by elopatin-uc3** [comment]
Agreed; I think most of this is covered in the admin UI. Closing
