### ISSUE TITLE
UCSD: Remove 856 subfield and 973 fields from MARC records 

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#808]
https://cdl.freshdesk.com/a/tickets/95233

#### Tasks
- [x] Remove 856 subfield originally requested via #379. This is causing intermittent MARC record validation errors for HC.
- [x] Also remove 973 fields
- [x] Send changes for review, prior to deployment
- [x] Remove the 793 fields entirely

**Comment by elopatin-uc3** [comment]
PRs for Stage and Prod:
https://github.com/CDLUC3/uc3-etds/pull/11
https://github.com/CDLUC3/uc3-etds/pull/10

**Comment by elopatin-uc3** [comment]
Deployed to production at 11:35AM on 10/7. Note that the Stage deploy requires git permissions cleanup (will consult Terry on this).

**Comment by elopatin-uc3** [comment]
Deployed to production. Stage branch also has this change, but could not deploy to Stage because of .git/objects permissions issue.
