### ISSUE TITLE
ETDs service: Create a method to regenerate a MARC record for a given ETD 

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#859]
#### Summary
Create a method to regenerate a MARC record for a given ETD, via a new script, utility or additional command line functionality in the current createmarc.py script.

Update:
Modification to the File Analyzer in the form of a new routine to update ProQuest provided .mrc files with eSchol links is the approach that's to be taken. Said routine will:
- Import a .mrc file from ProQuest
- Use the eSchol API to look up an ETD via title and author
- Add the eSchol ETD link to a corresponding record: insert and 856 field; link inserted into subfield "u".
- Add boilerplate text as needed and remove any unneeded PQ fields
- Export three files with PASS, SKIP, FAIL status appended to file name. 
  - SKIP = record was skipped
  - FAIL = no eSchol link found
  - PASS = eSchol link found and record updated 

#### Tasks
- [ ] Review boilerplate text present in records for each campus (UCI, UCM, UCSC). This will be added as needed to records via the File Analyzer routine.
- [ ] Confirm which PQ-supplied fields should be removed from the records output by the Analyzer.
- [ ] Implement Analyzer routine through its import function.

**Comment by elopatin-uc3** [comment]
New File Analyzer routine created. Research boilerplate text in UCM, UCI and UCSC records in order to add this to the routine.

**Comment by elopatin-uc3** [comment]
Notes regarding differences between ProQuest MARC files and those created by our ETDs service for (in this case) UCSC:

Extraneous fields that do not appear in ETD Service-generated UCM, UCI, UCSC records:
=040  \\$aMiAaPQ$cMiAaPQ
=500  \\$aPublisher info.: Dissertation/Thesis.
=506  \\$aThis item is not available from ProQuest Dissertations & Theses.
=506  \\$aThis item must not be added to any third party search indexes.
=506  \\$aThis item must not be sold to any third party vendors.

Unique to UCSC:
=006  m\\\\\o\\d\\\\\\\\
=007  cr|un|||||||||
=040  \\$aUMI$cCUZ
=049  \\$aCUZX
=655  \7$aDissertations, Academic$zUniversity of California, Santa Cruz$xComputer engineering.$2local
=655  \7$aDissertations, Academic$zUniversity of California, Santa Cruz$y2018$2local
=793  0\$aDigital Dissertations Database UCSC

To change field number - a 710 is used by PQ to note UCSC and what looks like department:
=710  20$aUniversity of California, Santa Cruz.$bBiomolecular Engineering and Bioinformatics.
(could we change this to 655, subfield 'x'?)

Adding 856, example (subfield 'u'):
=856  48$zeScholarship. Access restrictions may apply.$uhttp://escholarship.org/uc/item/04n983jj
=856  48$zDigital Dissertations Database. Restricted to UC Campuses.$uhttp://search.proquest.com/docview/2128012421

Example of 856 provided by PQ:
=856  \\$uhttp://gateway.proquest.com/openurl?url_ver=Z39.88-2004&rft_val_fmt=info:ofi/fmt:kev:mtx:dissertation&res_dat=xri:pqm&rft_dat=xri:pqdiss:10098579
