### ISSUE TITLE
Correct ETD database entries for UC Davis ETDs and generate corresponding MARC records

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#863]
A series of 215 UC Davis ETDs (the first three groups ingested) are missing MARC records because we missed adding associated code to the ETDs codebase. These are triggering "no local ID" errors in the etds log. The associated eSchol link and Merritt ingest metadata needs to be added for each in the etd.db.

#### Tasks
- [x] Add XSL template to support UCD
- [x] Update distribution list and UCD settings (delivery marc set to true) in config 
- [x] Add Merritt object info to merritt_ingest table in etd.db for each ETD

Not needed: Add eSchol link to marc_records table in etd.db for each ETD

Documentation for how to do so manually is here:
Section: "Addressing createmarc.py errors that are due to missing data in marc_records and merritt_ingest tables"
https://docs.google.com/document/d/1g2fgRAyoynGoBo8-yPOsOvTcviQ0lczIj6ssQnIXavQ/edit#

**Comment by elopatin-uc3** [comment]
Manually added entries for 10 ETDs that arrived on 11/04/2021.

Will observe if MARC records are generated for these at 1:30PM today.

**Comment by elopatin-uc3** [comment]
Terry has written two SQL queries for completing this work. One that obtains data from the INV DB and the other for inserting that data into the SqLite ETDs DB:
https://github.com/CDLUC3/merritt-tinker/blob/main/misc-sql/ucdetd.sql

**Comment by elopatin-uc3** [comment]
Waiting to hear back from UCD to approve MARC record format. Then we'll update the remaining 205 ETD entries in the merritt_ingest table, set their date_delivered entries in the marc_records table to null, ensure corresponding zip files are all available and manually run createmarc.py.

**Comment by elopatin-uc3** [comment]
Added database entries via the queries Terry created. Checked all entries and generated new records, which were sent to JC at Davis on 1/19/22.

**Comment by elopatin-uc3** [comment]
Committed changes on production branch.
