### ISSUE TITLE
[RELEASE] Replic Stage - update tracking

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#911]
# Service(s)
replication

# Github Issue Link(s)
https://github.com/CDLUC3/mrt-doc/issues/820

# Servers affected
uc3-mrtreplic01x2-stg
uc3-mrtreplic02x2-stg

# Source Code:
https://github.com/CDLUC3/mrt-inventory/commit/480157769a461ffb2bce92c577a3582e4b776b2b
https://github.com/CDLUC3/mrt-replic/commit/b67884bcfc5df67b889a646806dd33901980bb2c

Link(s) to tagged release(s)

# Jenkins/Build Info: (if applicable)
http://builds.cdlib.org/job/mrt-build-inv/58/console
http://builds.cdlib.org/job/mrt-build-replic/94/console

# MySQL changes - inv
~~~
ALTER TABLE inv_nodes_inv_objects
ADD COLUMN `replic_start` TIMESTAMP NULL,
ADD COLUMN `replic_size` BIGINT(20) UNSIGNED NULL,
ADD COLUMN `completion_status` ENUM('ok', 'fail', 'partial', 'unknown') NULL COLLATE 'utf8_general_ci',
ADD COLUMN `note` MEDIUMTEXT NULL COLLATE 'utf8_general_ci';

CREATE INDEX `irep_start` ON inv_nodes_inv_objects (`replic_start`) USING BTREE;
CREATE INDEX `irep_size` ON inv_nodes_inv_objects (`replic_size`) USING BTREE;
CREATE INDEX `irep_status` ON inv_nodes_inv_objects (`completion_status`) USING BTREE;
~~~

# Deployment Steps (if applicable)
- [ ] Update stage MySQL (uc3db-inv-stg.cdlib.org) - see above
- [ ] Update stage uc3-mrtreplic01x2-stg
- [ ] Update stage uc3-mrtreplic02x2-stg

**Comment by dloy** [comment]
Deploy performed to fix exception see note:
https://github.com/CDLUC3/mrt-doc/issues/820

# Servers affected
uc3-mrtreplic01x2-stg
uc3-mrtreplic02x2-stg

# Source Code:
https://github.com/CDLUC3/mrt-replic/commit/35b866344757768bb5066500602ede52fbbb9e56

# Jenkins/Build Info: (if applicable)
http://builds.cdlib.org/job/mrt-build-replic/95/console
