### ISSUE TITLE
Replicate Dryad collection content to Glacier

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#918]
#### Summary
Dryad will be establishing their own Glacier bucket. When Dryad content is set to be replicated to Glacier, we should use this new bucket. Additional decisions are forthcoming, some related to the below tasks in terms of additional information needed.

#### Tasks
- [x] Forecast costs of Glacier given current deposit rates for Dryad and incorporate an estimate for Glacier Deep Archive; provide to Marisa, John, Daniella (Eric)
- [x] Research technical requirements related to deposit of data into Glacier Deep Archive (David)
- [x] Determine preferred Production bucket name (David)
- [x] Determine preferred Stage bucket name (David)
- [x] Choose east coast data center - let IAS decide
- [x] Ask Ryan/Dryad to create the bucket
- [x] Start CDLSYS ticket to request new buckets and appropriate S3 access rights
  - [x] rights would likely match existing rights for Dryad bucket
  - [ ] Also look at the glacier vs s3 access rights to identify differences for a primary v secondary bucket 
- [ ] Configure new Dryad-owned Glacier bucket in Merritt: SSM parameters, additional database entries and configuration (David)
  - [x] Modify mrt-cloud yaml
  - [x] Deploy replic to include yaml changes - to ensure replication to new node
  - [x] Deploy audit to include yaml changes - to enable checksum of new nodes
  - [ ] Deploy storage to include yaml changes - for consistency
  - [ ] Deploy inventory to include yaml changes - for consistency
  - [ ] Update inv_nodes table to activate the new node 
- [ ] Kick off and monitor replication to new bucket via admin tool(Eric)
  - [ ] Start replication to new node
  - [ ] Halt replication to old node 
  - [ ] Once replication has caught up, start deletion of content from old node via admin tool (Eric + Terry)

**Comment by ryscher** [comment]
Bucket `dryad-assetstore-merritt-east` is now set up with the same permissions as the original `dryad-assetstore-merritt-west`. This will allow uploads using any storage class, though I assume the Merritt settings will only use one of the Glacier storage classes.

**Comment by elopatin-uc3** [comment]
Thanks @ryscher!

**Comment by elopatin-uc3** [comment]
Ryan is tracking bucket modification and creation via: https://github.com/CDL-Dryad/dryad-product-roadmap/issues/1775

**Comment by ryscher** [comment]
The new bucket has been created as `dryad-assetstore-merritt-stage-east`. It has the same access permissions as `dryad-assetstore-merritt-stage`. 

Both `dryad-assetstore-merritt-stage-east` and `dryad-assetstore-merritt-east` now have the lifecycle rules to transition content into Glacier.

**Comment by elopatin-uc3** [comment]
Thanks @ryscher !

**Comment by elopatin-uc3** [comment]
David submitted a CDLSYS ticket today to request establishing Merritt access to the two us-east-1 dryad S3 > Glacier Flexible buckets.

**Comment by dloy** [comment]
## Initial tests dryad buckets
I have run initial states tests using the dryad buckets with an expanded cloudConfig.yml that work on respective servers
### Stage test on uc3-mrtsandbox2-stg
- bucket: dryad-assetstore-merritt-stage-east
- node: 3642
### Prod test on uc3-mrtsandbox2-stg
- bucket: dryad-assetstore-merritt-east
- node: 3641
### cloudConfig.yml
~~~
---
node-table: "{!ENV: NODE_TABLE}"
services: &services
  aws-near: &aws-near
    type: aws-near
    service-properties:
      serviceType: aws
      accessMode: near-line
      region: us-west-2
      
  aws-near-east: &aws-near-east
    type: aws-near
    service-properties:
      serviceType: aws
      accessMode: near-line
      region: us-east-1

  aws-std: &aws-std
    type: aws-std
    service-properties:
      serviceType: aws
      accessMode: on-line
      storageClass: Standard
      region: us-west-2

  ch-unm-prd: &ch-unm-prd
    type: ch-unm-prd
    service-properties:
      serviceType: cloudhost
      base: http://oneshare.unm.edu:8080/cloudhost

  minio-sdsc-new: &minio-sdsc-new
    type: minio-sdsc
    service-properties:
      serviceType: minio
      endPoint: https://cdl.s3.sdsc.edu:443
      accessKey: "{!SSM: cloud/nodes/sdsc-accessKey !DEFAULT: SSMFAIL}"
      secretKey: "{!SSM: cloud/nodes/sdsc-secretKey !DEFAULT: SSMFAIL}"

  minio-docker: &minio-docker
    type: minio-docker
    service-properties:
      serviceType: minio
      # Note, we use ec2_host:8088 on our ec2 docker test machine
      endPoint: "http://{!ENV: MRT_MINIO_HOST !DEFAULT: my-minio-localhost-alias}:{!ENV: MRT_MINIO_PORT !DEFAULT: 8088}"
      accessKey: minioadmin
      secretKey: minioadmin

  wasabi-east: &wasabi-east
    type: wasabi-east
    service-properties:
      serviceType: wasabi
      endPoint: https://s3.us-east-2.wasabisys.com:443
      accessKey: "{!SSM: cloud/nodes/wasabi-accessKey !DEFAULT: SSMFAIL}"
      secretKey: "{!SSM: cloud/nodes/wasabi-secretKey !DEFAULT: SSMFAIL}"
      regionName: us-east-2

nodes-tables:
  nodes-prod:
      - # AWS Standard
        identifier: 5001
        <<: *aws-std
        bucket: uc3-s3mrt5001-prd
        desc: "AWS standard prod"

      - # AWS Glacier
        identifier: 6001
        <<: *aws-near
        bucket: uc3-s3mrt6001-prd
        desc: "AWS glacier prod"

      - # Merritt Cloudhost - on AWS
        identifier: 7001
        <<: *aws-std
        bucket: uc3-s3mrt1001-prd
        desc: "###ArchiveNode"

      - # UNM Remote Storage
        identifier: 4001
        <<: *aws-std
        bucket: dryad-assetstore-merritt-west
        desc: "ONEShare"

      - # Dryad, AWS Standard
        identifier: 3041
        <<: *aws-std
        bucket: dryad-assetstore-merritt-west
        desc: "Merritt Dryad prod"

      - # Dryad, AWS Glacier
        identifier: 3641
        <<: *aws-near-east
        bucket: dryad-assetstore-merritt-east
        desc: "Merritt Dryad Glacier prod"

      - # SDSC Minio, Mar 2020
        identifier: 9501
        <<: *minio-sdsc-new
        bucket: cdl.sdsc.prod
        desc: "sdsc minio prod"

      - # Wasabi
        identifier: 2001
        <<: *wasabi-east
        bucket: uc3-wasabi-useast-2.prod
        desc: "wasabi s3 prod"

  nodes-stage:
      - # AWS Standard
        identifier: 5001
        <<: *aws-std
        bucket: uc3-s3mrt5001-stg
        desc: "AWS standard stage"

      - # AWS Glacier
        identifier: 6001
        <<: *aws-near
        bucket: uc3-s3mrt6001-stg
        desc: "AWS glacier stage"

      - # Merritt Cloudhost - on AWS
        identifier: 7001
        <<: *aws-std
        bucket: uc3-s3mrt1001-stg
        desc: "###ArchiveNode"

      - # UNM Remote Storage
        identifier: 4101
        <<: *minio-sdsc-new
        bucket: cdl.sdsc.stg4101
        desc: "ONEShare stage"

      - # Dryad, AWS Standard
        identifier: 3042
        <<: *aws-std
        bucket: dryad-assetstore-merritt-stage
        desc: "Merritt Dryad stage"

      - # Dryad, AWS Glacier
        identifier: 3642
        <<: *aws-near-east
        bucket: dryad-assetstore-merritt-stage-east
        desc: "Merritt Dryad Glacier stage"

      - # SDSC Minio
        identifier: 9502
        <<: *minio-sdsc-new
        bucket: cdl.sdsc.stage
        desc: "sdsc minio stage"

      - # Wasabi
        identifier: 2002
        <<: *wasabi-east
        bucket: uc3-wasabi-useast-2.stage
        desc: "wasabi s3"

  nodes-dev:
      - # AWS Standard
        identifier: 5003
        <<: *aws-std
        bucket: uc3-s3mrt5001-dev
        desc: "AWS standard stage"

      - # AWS Glacier
        identifier: 6003
        <<: *aws-near
        bucket: uc3-s3mrt6001-dev
        desc: "AWS glacier stage"

      - # Merritt Cloudhost - on AWS
        identifier: 7001
        <<: *aws-std
        bucket: uc3-s3mrt1001-dev
        desc: "###ArchiveNode"

      - # SDSC Minio
        identifier: 9503
        <<: *minio-sdsc-new
        bucket: cdl.sdsc.dev
        desc: "sdsc minio"

      - # Wasabi
        identifier: 2003
        <<: *wasabi-east
        bucket: uc3-wasabi-useast-2.dev
        desc: "wasabi s3"

  nodes-pairtree-docker:
      - # Minio Docker
        identifier: 7777
        <<: *minio-docker
        bucket: my-bucket
        desc: "docker minio 7777"
      - # Minio Docker Replic
        identifier: 8888
        <<: *minio-docker
        bucket: my-bucket-repl
        desc: "docker minio 8888"
~~~

**Comment by dloy** [comment]
## Start replication to new node
An object is replicated if:
- the collection for an object matches the inv_collections_inv_nodes.inv_collection_id
- the inv_nodes_inv_objects.replicated for that object is null OR a replication add request is issued for object.

### create new collection-node entry
~~~
insert into inv_collections_inv_nodes
set inv_collection_id=420, inv_node_id=18
~~~
This insert will add the Dryad glacier node (3641=id18) as a replica for all Dryad collection (420) content
### distribute release
~~~
update inv_nodes_inv_objects
set replicated = null
where role='primary'
and inv_nodes_inv_objects.id in (
...
)
~~~
Setting the replicated=null triggers replic to test and build replica content. It may be required to stagger this process considering the range of content size. One Dryad object (ark:/13030/m5w44t5h) > 1.1T with largest Dryad file 181G.

An additional mechanism for forcing replication on an object is the replic "add" API:
~~~
curl -X POST 'http://localhost:38001/mrtreplic/add/ark%3A%2F13030%2Fm5w44t5h?t=xml'
~~~
This mechanism will only work if the object in question allows replication.

**Comment by terrywbrady** [comment]
We have some admin tools to handle some to the sql bits listed above.  Those tools are not smart enough to throttle/stagger the work.  @dloy and @elopatin-uc3 , fyi
