### ISSUE TITLE
[RELEASE] Replic Prod - update tracking 2/7/22

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#925]
# Service(s)
replication

# Github Issue Link(s)
https://github.com/CDLUC3/mrt-doc/issues/820

# Servers affected
uc3-mrtreplic01x2-prd
uc3-mrtreplic02x2-prd

# Source Code:
https://github.com/CDLUC3/mrt-inventory/commit/480157769a461ffb2bce92c577a3582e4b776b2b
https://github.com/CDLUC3/mrt-replic/commit/b67884bcfc5df67b889a646806dd33901980bb2c

Link(s) to tagged release(s)

# Jenkins/Build Info: (if applicable)
http://builds.cdlib.org/job/mrt-build-inv/58/console
http://builds.cdlib.org/job/mrt-build-replic/96/console

# MySQL changes - inv
~~~
ALTER TABLE inv_nodes_inv_objects
ADD COLUMN `replic_start` TIMESTAMP NULL,
ADD COLUMN `replic_size` BIGINT(20) UNSIGNED NULL,
ADD COLUMN `completion_status` ENUM('ok', 'fail', 'partial', 'unknown') NULL COLLATE 'utf8_general_ci',
ADD COLUMN `note` MEDIUMTEXT NULL COLLATE 'utf8_general_ci';

CREATE INDEX `irep_start` ON inv_nodes_inv_objects (`replic_start`) USING BTREE;
CREATE INDEX `irep_size` ON inv_nodes_inv_objects (`replic_size`) USING BTREE;
CREATE INDEX `irep_status` ON inv_nodes_inv_objects (`completion_status`) USING BTREE;
~~~

# Deploy MySQL change
Ran into a potential problem that creating the new 4 columns might take a large amount of time and potentially impact other microservices - particularly inventory.  A variety of tests indicated that the update time should not take more than 6 minutes. 

To prevent any side issues with Dryad and other Merritt services, the changes will be performed while the system is paused. 

- [x] Scheduling on this needs to be confirmed.
- [x] Update prod MySQL (uc3db-inv-prd.cdlib.org) 

# Deployment Steps (if applicable)
- [x] Update prod uc3-mrtreplic01x2-stg
- [x] Update prod uc3-mrtreplic02x2-stg
