### ISSUE TITLE
Production cleanup for ETDs for 2022-02-05 issue

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#929]
#### Summary
82 UCSB and 1 UCLA ETD zips were ready to ingest on 2022-02-05, however we had a production ingest issue. Only three of the UCSB ETDs were ingested. Upon investigation, the only table in the ETD db that was updated was pq_metadata. The plan to reset the system to a state where it will re-submit the remaining ETDs is as follows:

#### Tasks
- [x] Backup db and download a copy
- [x] Remove pq_metadata entries for new entries
- [x] KEEP entries for few that were ingested: DONE
		Sanderson, Richard:  Remote detection and localization...
		Jones, CJ E:  Governing Bodies: Trans Politics...
		Ma, Xu:  Development of a General SN2...
- [x] Re-ingest by copying zip files in 20220205 folder back to SFTP
- [ ] Clean up ingest EFS
- [x] Run getetds.py (will occur 2022-02-08 at 7:30am)

**Comment by elopatin-uc3** [comment]
getetds run successful this morning; will clean up EFS next

**Comment by elopatin-uc3** [comment]
Cleanup complete; moving to Done.
