### ISSUE TITLE
Create Micro Service Unit Tests

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#985]
Based on a conversation with @ashleygould ...

We have a number of upcoming projects that will touch ALL of our microservice code.
- build refactor
- maven refactor
- logging
- java 11
- routine jar patching

The creation of repo level unit tests would help significantly with these efforts.

Currently, the Merritt UI relies on a test database to perform unit tests.  This is most often run as a docker container.

## What is needed
- Ingest: 
  - https://github.com/CDLUC3/mrt-ingest/pull/46
  - Zookeeper instance
  - Mock Storage
  - Mock INV
- Store
  - S3 storage service (Minio container)
- Audit   
  - S3 storage service (Minio container)
  - Database (MySQL container)
- Replic   
  - S3 storage service (Minio container)
  - Database (MySQL container)
- Inventory
  - Mock storage
  - Database (MySQL container)

## Tasks
- [ ] Choose test framework (I presume JUnit)
- [ ] Choose mock framework? (for mocking API calls)
- [ ] Determine how to launch dependent containers from `mvn test`
- [ ] Write new code/libraries to populate test containers to support tests
- [ ] Write unit tests
- [ ] Explore/evaluate test coverage tools

## Notes

Verify `scope` for maven dependencies esp junit:

From https://maven.apache.org/ref/3.8.5/maven-model/maven.html
```
The scope of the dependency - compile, runtime, test, system, and provided. Used to calculate the various classpaths used for compilation, testing, and so on. It also assists in determining which artifacts to include in a distribution of this project. For more information, see [the dependency mechanism](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html). The default scope is compile.
```

**Comment by terrywbrady** [comment]
Here is an example from DSpace that runs integration tests with containers from GitHub actions
- https://github.com/DSpace/dspace-angular/blob/main/.github/workflows/build.yml#L90-L94

Here is a mvn plugin that will launch docker-compose, but I am not sure how widely used it is
- https://github.com/br4chu/docker-compose-maven-plugin/blob/master/README.md
